prody/ProDy

- prody/ensemble/ensemble.py
Fixes https://github.com/prody/ProDy/issues/181
> Changed Ensemble.getDeviations() to account for selected atom indices

- prody/dynamics/__init__.py
- prody/dynamics/sm.py
- prody/dynamics/smtools.c
- prody/dynamics/smtools.h
- setup.py
I added 3 files sm.py (main python file), smtools.c (source code for cpython) and smtools.h (header file) to calculate the stiffness matrix in dynamics module. This is the development version for stiffness matrix.
> Stiffness matrix calculation addition to prody.dynamics module. 

- prody/dynamics/analysis.py
- prody/dynamics/anm.py
- prody/dynamics/gnm.py
- prody/dynamics/plotting.py
- prody/dynamics/vmdfile.py
- prody/proteins/header.py
- prody/tests/datafiles/__init__.py
- prody/tests/dynamics/test_enms.py
I added new function which generates deformability profile based on mechanical stiffness matrix. It creates PDB file with mean values of stiffness in Occupancy column. It created also TCL file which put structure in VMD and creates properly representation to see the results. I moved mean value calculations from ANM to vmdfile. Now they are a part of  getDeformProfile function. 
< This function was consulted with Ivet >
Karolina
> New module related to MechStiffness - deformability profile

- prody/atomic/subset.py
> fix windows numpy datatype conflicts in selection

- prody/ensemble/ensemble.py
Now ``ensemble.addCoordsets()`` can take instances with ``getCoordsets()`` as well as ``getCoords()`` as input.
> small improvement related to #278

- prody/atomic/select.py
Thanks for the input and fix from [jmbromley](https://github.com/jmbromley).
> fix selection issue related to #252 #253

- prody/atomic/select.py
- prody/dynamics/anm.py
Thanks for what [jmbromley](https://github.com/jmbromley) did in #251.
> fix selection of insertions (same with #251)

- prody/utilities/logger.py
Fix: if step is a long, this check will fail on windows.
> A small fix in logger

- prody/database/pfam.py
update the link of pfam in pfam.py by Mao
> fixes by Mao #263

- prody/database/pfam.py
- Fix the compatibility of searchPfam with Python 2.7.11 (#282);
- Update the link of HMMER search service.
> Fixes in pfam.py

- prody/trajectory/trajectory.py
> Fix the indexing issue of getCoordsets().

- prody/ensemble/conformation.py
- fix a bug in PDBConformation.__repr__()
> fix a bug in ensemble.conformation.PDBConformation

- prody/atomic/atom.py
- prody/proteins/pdbfile.py
- prody/utilities/misctools.py
> Fix getMasses()

- prody/dynamics/gnm.py
- prody/dynamics/mode.py
- prody/dynamics/modeset.py
- prody/dynamics/plotting.py
Added feature:
- Identifying hinge sites. Now GNM class has two additional functions _calcHinges_ and _getHinges_. Mode and ModeSet objects can also return hinge sites if they are calculated from GNM.
- Plotting hinge site. _showMode_ and _showSqFlucts_ now have an option _hinge_ to plot the hinge sites (on by default). Same features in _showScaledFlucts_ and _showNormedFlucts_ are remained to be implemented.
> Implemented hinge sites

- prody/dynamics/gnm.py
a small modification to make sure that hinge sites are sorted in ascending order.
> hinge function modification

- prody/proteins/functions.py
Test case on a LeuT structure (PDBID: 3TT3, 3 chains). Protein colored based on GNM mode 1:
Based on GNM mode 2:
> Implementation of color coded by mode in showProtein

- prody/dynamics/gnm.py
- when hinge sites are not calculated, throw a warning instead of an error.
> A small fix to hinge sites

- prody/proteins/__init__.py
- prody/proteins/ciffile.py
1. ciffile.py was created in proteins akin to pdbfile.py for parse mmCIF files
2. __init__.py in proteins was updated to include ciffile.py functions and documentation
> Added capability for parsing mmCIF files

- prody/dynamics/analysis.py
- prody/dynamics/plotting.py
calcPerturbResponse now has an option to use the covariance matrix
directly rather than applying forces
> Updated dynamics/analysis.py

- prody/atomic/__init__.py
- prody/atomic/chain.py
> Add `getHierView` to `Chain`

- prody/chromatin/__init__.py
- prody/chromatin/cluster.py
- prody/chromatin/hic.py
－Implemented domain identification;
－Implemented `saveHiC` and `loadHiC`.
> Complete Hi-C module.

- prody/dynamics/analysis.py
- prody/dynamics/plotting.py
This a comment just so it doesn't say no comment. These changes don't really do much and are described in the respective commits anyway.
> Some minor changes before the release

- prody/dynamics/plotting.py
Added a new kwargs "new_fig" to plotting functions to control if a new figure needs to be created prior to plotting. Default is `True`.
I didn't add this kwargs to "complex" plotting functions. By "complex" I mean functions which create subplots, because these functions are unlikely to be plotted on top of the others.
> A minor change to plotting functions

- prody/dynamics/vmdfile.py
- prody/proteins/localpdb.py
－Added an optional argument to fetchPDB to force using HTTP or FTP. parsePDB shares this argument.
－Fixed a Python 2 and 3 compatibility issue in writeVMDstiffness (xrange).
> Two changes on parsePDB and writeVMDstiffness

- prody/atomic/__init__.py
- prody/atomic/atomic.py
- prody/atomic/chain.py
- prody/atomic/select.py
- prody/dynamics/analysis.py
Now ALL Atomic classes (especially Selection), have function getSequence().
> getSequence for ALL Atomic classes

- prody/atomic/atomgroup.py
The setData method of AtomMap now can handle scalar input, which becomes more consistent with the same method of Selection.
P.S. maybe it is not important. It is just low-level.
> *Important* change to the setData method of AtomMap

- prody/atomic/atomgroup.py
> Now getHierView will always return the updated HierView.

- prody/ensemble/functions.py
- prody/proteins/pdbfile.py
- Fixed a small bug in trimPDBEnsemble
- Added an option to writePDB whether the secondary structure information should be written
- Added addPDBEnsemble function
> Some small fixes

- prody/dynamics/pca.py
- prody/ensemble/functions.py
- prody/proteins/functions.py
> Revert "Several fixes"

- prody/dynamics/pca.py
- prody/ensemble/functions.py
- prody/proteins/functions.py
> Revert "Revert "Several fixes""

- prody/dynamics/analysis.py
- prody/ensemble/functions.py
set normMatrix to True and move repeats into kwargs for calcPerturbResponse.
> Small changes to calcPerturbResponse

- prody/dynamics/analysis.py
- prody/dynamics/plotting.py
Added an option to projection calculation & visualization that normalizes the deformation vector or not. The default is True.
> A small change to projection calculation and visualization

- prody/dynamics/plotting.py
Added a plotting function called showMatrix that can be used to plot a matrix with curves on top and left.
> Added showMatrix function

- prody/dynamics/plotting.py
Appropriate documentation was also added
> Added return of the axes for showMatrix

- prody/atomic/hierview.py
- prody/utilities/misctools.py
Fixed a problem where list.count may raise error when counting the number of `None` when using the newest version of numpy.
> Problem fixed in hierview.py

- prody/proteins/ciffile.py
Not sure how that is but it seem right
> The sum total is deleting a line

- prody/proteins/__init__.py
- prody/proteins/starfile.py
STAR files are parsed into nested dictionaries and nested dictionaries can be written back out as STAR files.
> Added STAR file parsing and writing capabilities

- prody/dynamics/analysis.py
- add an option to calcCrossCorr to determine if the resulting matrix is normalized or not.
> Small change to calcCrossCorr

- prody/dynamics/plotting.py
- prody/proteins/starfile.py
Here's a screenshot showing the results
> showMatrix and showPerturbResponse now work

- prody/proteins/wwpdb.py
The path changed so it was failing and now it works again
> Fixed fetchPDBviaFTP

- prody/proteins/compare.py
- Added mapChainByChain to proteins/compare.py as an addition to mapOntoChain. It can be useful in the cases where strictly chains with the same chain identifiers needed to be mapped.
- Added two arguments to mapOntoChain: alignment and alignments, so that users can provide their own alignments. 
**alignment** (tuple or list): a duplet of pre-aligned sequences with gaps.
**alignments** (dictionary): a dictionary of alignments with chain identifiers being the keys. Note that if a chain is not included in this dictionary then *alignment* will be used.
> Changes to proteins/compare.py

- prody/chromatin/functions.py
- prody/dynamics/compare.py
Implemented matchModes function which does what pairModes does for multiple modesets
> Implemented matchModes

- prody/__init__.py
- prody/dynamics/__init__.py
- prody/dynamics/analysis.py
- prody/dynamics/plotting.py
- prody/dynamics/signature.py
- prody/ensemble/functions.py
- prody/utilities/__init__.py
- prody/utilities/catchall.py
- prody/utilities/misctools.py
- Reorganized utilities and a few other things to have an extra catchall file with functions such as clusterMatrix that are general but accessible to users.
- Move signdy related functions to signature.py.
> SignDy related changes

- prody/dynamics/gnm.py
- prody/dynamics/plotting.py
- prody/dynamics/signature.py
- prody/utilities/catchall.py
- bug fixes
- added a basic plotting function to catchall.py
> Added showData to catchall

- prody/dynamics/functions.py
- prody/dynamics/plotting.py
- prody/dynamics/signature.py
- prody/utilities/logger.py
Now calcEnsembleENMs shows a progress bar instead of flushing messages when running
> Changed calcEnsembleENMs messages

- prody/utilities/catchall.py
This function uses a tree to reorder a matrix and also return indices that can be used for reordering other things.
> Made function reorderMatrix

- prody/dynamics/plotting.py
- prody/utilities/catchall.py
This function uses a tree to reorder a matrix and also return indices that can be used for reordering other things.
Setting the current axis in showMatrix lets users or functions set things like titles on the matrix subplot afterwards.
> Made a function findSubgroups

- prody/dynamics/compare.py
- prody/dynamics/plotting.py
- prody/dynamics/signature.py
- prody/utilities/catchall.py
－ Added an option to pairModes and matchModes so that the function can return indices of modes instead of Mode instances.
－Added showMatrix to catchall.py and the original function was renamed to showAtomicMatrix. The functions still need some tweaks to work properly.
> Changes to matchModes and showMatrix

- prody/dynamics/compare.py
- prody/dynamics/signature.py
- prody/ensemble/dali.py
Changes colormap in showAverageCrossCorr; Returns matrix for matchModes if index=True
> Small changes in showAverageCrossCorr and matchModes

- prody/dynamics/plotting.py
- prody/dynamics/signature.py
- prody/utilities/catchall.py
- Modified showMatrix so that it works properly.
- Changed the output of plotting functions to be consistent with matplotlib. Now plotting functions returns graphic objects, e.g. lines, polycollections, etc.
> Tweaks to plotting functions

- prody/dynamics/plotting.py
- prody/dynamics/signature.py
- prody/utilities/catchall.py
- prody/utilities/legacy.py
- further improvements on showMatrix and showAtomicData,
- moved legacy code to utilities.
> Improvement of plotting functions (plotting chains, domains, tick labels, etc)

- prody/proteins/blastpdb.py
- prody/proteins/psiblast.py
>  Changes trying to get psiblast working 

- prody/dynamics/compare.py
- prody/dynamics/functions.py
- prody/dynamics/plotting.py
- prody/dynamics/signature.py
- prody/ensemble/ensemble.py
- prody/ensemble/functions.py
- prody/ensemble/pdbensemble.py
- prody/utilities/catchall.py
- prody/utilities/misctools.py
bug fixes for the selection function in ensemble module
> Improvements and bug fixes

- prody/dynamics/compare.py
- prody/dynamics/signature.py
- prody/utilities/catchall.py
- implementation of Signature class
- now pairModes and matchModes return ModeSets instances as output
- rename getSignatureProfile to calcSignatureProfile
- rename calcAvgCrossCorr to calcSignatureCrossCorr
- style changes to showAvgCrossCorr
- now calcSignatureCrossCorr accepts Ensemble instance as input
> Changes related to SignDy

- prody/dynamics/signature.py
- bug fixes
- renamed show & calcSignatureProfile to show & calcSignatureMobility
> Bug fixes and renaming 

- prody/dynamics/signature.py
- improved ModeEnsemble class. Now it has getVariance and getVariances
- adapted showSignatureVariances to new data structure
> Improvements of ModeEnsemble

- prody/dynamics/signature.py
－ ModeEnsemble now supports indexing with mode number(s). For example, to obtain the first 10 modes in the ensemble:
`enms_top10 = enms[:, :10]`
the first argument is the index of modesets, and the second is mode index.
- SignDy functions now do not have index as an argument as the ensemble can be indexed by:
```
showSignatureMode(enms[:, 0])
showSignatureSqFlucts(enms[:, :10])
```
> Improvement of ModeEnsemble and SignDy functions

- prody/dynamics/functions.py
- prody/dynamics/plotting.py
- improvements in robustness when dealing with unicode strings
- add node_shape option to showTree_networkx
> Improvements in showTree_networkx etc

- prody/ensemble/functions.py
- prody/sequence/analysis.py
- prody/sequence/msafile.py
We may want to remove the writeClustal function but writePIR should be good.
> more MSA writing options

- prody/ensemble/dali.py
- prody/proteins/wwpdb.py
fix https url in fetchPDBviaHTTP.
add try...except for buildDaliEnsemble (there are mistakes from dali results).
> fetchPDBviaHTTP and buildDaliEnsemble

- prody/database/__init__.py
- prody/database/uniprot.py
- prody/ensemble/functions.py
- prody/proteins/compare.py
- prody/proteins/header.py
- prody/sequence/analysis.py
For example, PDB 5CNK has multiple blocks with 'APPLY THE FOLLOWING TO CHAINS:' lines and then 'BIOMT' lines.
>  Fixed _getBiomoltrans to work with new PDBs too

- header.py
- prody/database/__init__.py
- prody/database/uniprot.py
- prody/utilities/misctools.py
Don't know why the header file became untracked and had to be added again
> Added queryUniprot

- prody/database/pfam.py
- prody/database/uniprot.py
- prody/proteins/header.py
- prody/proteins/pdbfile.py
- prody/sequence/analysis.py
- prody/sequence/msafile.py
Also minor changes to some others
> Fixes to alignSequencesByChain and writeClustal

- prody/ensemble/functions.py
It converts it into an alignments list
> buildPDBEnsemble can now take an MSA

- prody/dynamics/plotting.py
- prody/ensemble/functions.py
- prody/proteins/compare.py
- prody/sequence/analysis.py
- prody/utilities/catchall.py
It can now handle inputs with segments, which are obtained from biomolecules
> Bug fix to buildPDBEnsemble

- prody/dynamics/plotting.py
- prody/utilities/catchall.py
Fixed a bug for reorderMatrix; 
Pass parameter k to networkx.spring_layout for showTree_networkx.
> Fixed a bug for reorderMatrix

- prody/dynamics/signature.py
- prody/ensemble/ensemble.py
- prody/sequence/analysis.py
- Implemented weighted average and standard deviation for signature;
- Fixed 'bulb' issue when using `ModeEnsemble.getEigvecs`;
- Other minor typo or bug fixes.
> Weighted average and standard deviation for Signature

- prody/ensemble/conformation.py
- prody/ensemble/ensemble.py
- prody/ensemble/functions.py
- prody/ensemble/pdbensemble.py
- prody/sequence/msa.py
- prody/tests/sequence/test_msa.py
- Associated PDBEnsemble with an MSA and added `getSequence ` to `PDBConformation`.
- Added `__add__` operation to MSA class.
- Now MSA class accepts list or array of strings, as long as the sequences have equal length if `aligned=True`, or gaps will be added to the end if they don't and `aligned=False`.
>  Associated PDBEnsemble with an MSA

- prody/ensemble/pdbensemble.py
- prody/sequence/msa.py
- prody/sequence/sequence.py
- prody/tests/sequence/test_msa.py
- prody/utilities/misctools.py
- Now copying MSA does not need to copy the mapping, internally the class will make sure the labels and the mapping are consistent.
- Added `MSA.extend` that accepts `MSA`, `Sequence`, or numpy array (which will be converted to chararray first).
- Added more tests to MSA for addition and extension.
- Changes to `PDBEnsemble.addCoordsets` to improve efficiency.
- Minor bug fixes.
> Changes to MSA

- prody/atomic/functions.py
- prody/dynamics/editing.py
- prody/ensemble/ensemble.py
- prody/ensemble/functions.py
- prody/tests/ensemble/test_ensemble.py
－Moved and renamed `prody.dynamics.slice` to `prody.atomic.sliceAtoms`
－Changed ensemble and reduceModel atoms slicing to existing a ProDy function (`sliceAtoms`)
> Switch ensemble slicing to existing a ProDy function

- prody/dynamics/signature.py
`showSignatureMode` now can display ANM modes.
> Added support to ANM for signature functions

- prody/ensemble/functions.py
- prody/sequence/msa.py
- prody/tests/ensemble/test_functions.py
- Changes made result in smaller ensemble size saved on local disk.
- Added a test on trimPDBEnsemble related to the associated MSA.
- Bug fixes in saveEnsemble and MSA indexing (thanks to the new test I was able to identify this bug which is critical but not obvious).
> Improvements and bug fixes in ensemble functions

- prody/proteins/ciffile.py
- prody/proteins/compare.py
Also made mapChainByChain use mapOntoChainByAlignment, which would default back to mapOntoChain if there is no alignment.
>  removed debug reporting in parseCIF 

- prody/ensemble/dali.py
- prody/proteins/compare.py
- prody/proteins/pdbfile.py
- [mapOntoChain] Now the function uses trivial mapping first no matter what but the result needs to meet a very high criterion (seqid > 0.9). This will result in faster and more accurate alignment of sequences from the same protein with minor mutations.
- [parsePDB] Reverted the addition of ``report``. The messages will be automatically suppressed if a ``LOGGER.progress`` is initiated.
> Changes to mapOntoChain

- prody/dynamics/signature.py
These now take the default order rather than the reverse.
> recolored showSignatureVariance histogram

- prody/database/uniprot.py
- prody/dynamics/anm.py
- prody/dynamics/gnm.py
- prody/dynamics/pca.py
If we use `lower()` with `is` then we get False. If we don't use `lower` then using `is` gives True.
> bug fix to n_modes='all'

- prody/dynamics/compare.py
- prody/dynamics/signature.py
Also tried to make the LOGGER show progress of matching modes but that doesn't seem to have worked.
>  added calcSignatureOverlaps and showSignatureOverlapsDiag 

- prody/dynamics/signature.py
-[SignDy] Added ``calcSignatureCollectivity`` and ``showSignatureCollectivity``.
-[sdarray] Modified the behavior of slicing.
> Multiple changes

- prody/database/pfam.py
- prody/ensemble/dali.py
Also renamed it to parsePfamPDBs
>  updated fetchPfamPDBs to use current pdbmap.gz

- prody/database/pfam.py
- Now data is streamed from FTP, so no local file is generated.
- Merged `pfam_acc` and `query`. It is a good practice that a function has an explicit input when it is expected.
- Swap the position of `results` and  `data_dicts` - the user would expect the `results` coming first.
- PY3K compatibility changes.
> Possible improvements of parsePfamPDBs

- docs/devel/xplatform.rst
- prody/apps/prody_apps/prody_fetch.py
- prody/atomic/atommap.py
- prody/atomic/residue.py
- prody/chromatin/functions.py
- prody/chromatin/hic.py
- prody/chromatin/norm.py
- prody/dynamics/analysis.py
- prody/dynamics/anm.py
- prody/dynamics/bbenm.py
- prody/dynamics/exanm.py
- prody/dynamics/functions.py
- prody/dynamics/gnm.py
- prody/dynamics/pca.py
- prody/dynamics/plotting.py
- prody/dynamics/rtb.py
- prody/ensemble/ensemble.py
- prody/ensemble/functions.py
- prody/ensemble/pdbensemble.py
- prody/sequence/analysis.py
- prody/trajectory/dcdfile.py
- prody/trajectory/trajbase.py
－All the ``None`` are changed to **None**.
－All the ``True`` are changed to **True**.
－All the ``False`` are changed to **False**.
> Documentation consistency fix

- prody/dynamics/plotting.py
- prody/dynamics/signature.py
- prody/ensemble/functions.py
- prody/sequence/msa.py
- prody/utilities/catchall.py
- Bug fixes to `specMergeMSA`.
- enhanced PY3 compatibility to loadEnsemble
- Renamed showLine (and showAtomicLine) to showLines (showAtomicLines)
> Small changes

- prody/dynamics/functions.py
- prody/dynamics/signature.py
- prody/ensemble/ensemble.py
- prody/ensemble/functions.py
- prody/ensemble/pdbensemble.py
- prody/utilities/misctools.py
- Implemented save(load)ModeEnsemble.
- Compatibility fixes to loadModel.
> Implemented save(load)ModeEnsemble

- prody/database/cath.py
- prody/database/pfam.py
Added a reference to the parent to `CATHElement`.
> Bug fixes and improvements to CATH classes

- prody/proteins/compare.py
- prody/utilities/tnt/tnt_sparse_matrix_csr.h
- setup.py
fix for issue #666 according to [this link](https://bugs.llvm.org/show_bug.cgi?id=9627).
> fix to cealign for clang (MacOS)

- prody/dynamics/gnm.py
This was spotted in issue #413
> correction to getNormDistFluct 

- prody/trajectory/dcdfile.py
> fixed a small bug in parseDCD

- prody/proteins/pdbfile.py
> added charges to _parsePDBLines when format is PDB

- prody/database/pfam.py
> Revert "pfam fixes for missing xml"

- prody/dynamics/plotting.py
- prody/dynamics/signature.py
- prody/proteins/functions.py
- prody/utilities/catchall.py
- allow signature plotting function to use the gap option.
- allow signature functions to use gap.
- fixed a problem of using overlay on single-chain structure.
> Fixes related to plotting functions

- prody/proteins/functions.py
- prody/utilities/drawtools.py
- prody/utilities/misctools.py
If use `matplotlib`, the modes are depicted by arrows. If use `py3Dmol`, an animation is generated.
> Allowed showProtein to display ANM modes

- prody/chromatin/cluster.py
- prody/chromatin/hic.py
- prody/proteins/functions.py
- Improved view3D to have consistent argument names with showProtein;
- Added the option to display arrows instead of showing animations for ANM modes (and set this as the default behavior);
- PY3K compatibility fix to chromatin module.
> Consistency changes to view3D

- prody/database/dali.py
- prody/database/pfam.py
- prody/measure/measure.py
- prody/proteins/compare.py
- prody/sequence/analysis.py
- prody/utilities/legacy.py
There are also a few minor changes in error messages
> added a function for getting an MSA for biopython pairwise alignment and fixes to dali

- prody/database/dali.py
Also, the requests package is used instead of urllib and urllib2.
> Dali input with local PDB

- prody/dynamics/signature.py
- prody/ensemble/ensemble.py
- prody/tests/apps/test_prody_anm.py
- prody/tests/apps/test_prody_catdcd.py
- prody/tests/apps/test_prody_examples.py
- prody/tests/apps/test_prody_gnm.py
- prody/tests/apps/test_prody_pca.py
- prody/tests/atomic/test_select.py
- prody/tests/dynamics/test_enms.py
- prody/tests/dynamics/test_signature.py
- prody/tests/proteins/test_dssp.py
- prody/tests/proteins/test_localpdb.py
- prody/tests/proteins/test_pdbfile.py
- prody/tests/proteins/test_wwpdb.py
- prody/utilities/legacy.py
- Now the variance bar shows the distribution of the variances like a histogram except that it uses colors instead of heights of bars to represent the density.
- The purpose of this pull request is also to reproduce the previous check errors.
> Implemented the new variance bar and added documentation

- prody/dynamics/signature.py
Otherwise the coords of the original atoms are updated on line 707.
> changed atoms in calcEnsembleENMs to a copy

- prody/dynamics/signature.py
fix to calcEnsembleENMs to make select work again (and fix the coordinate changing problem)
> Fix to calcEnsembleENMs

- prody/chromatin/functions.py
- prody/chromatin/hic.py
- prody/dynamics/functions.py
- prody/dynamics/gnm.py
- prody/dynamics/modeset.py
- prody/dynamics/signature.py
Renamed TrimmedGNM to MaskedGNM just to be more consistent with the naming in numpy where there is a MaskedArray.
> Bug fixes and renamed TrimmedGNM to MaskedGNM

- prody/trajectory/trajfile.py
A fix to the bug reported in #748.
> Fixed a bug in trajfile

- prody/database/dali.py
- prody/proteins/functions.py
- prody/tests/sequence/test_msafile.py
- prody/utilities/misctools.py
- `searchDali` now uses the stream instead of writing a temporary file while uploading local files.
- Removed `isLocal` argument as the input type can be decided by the `pdb` argument.
- `pdb` argument now accepts `AtomGroup`.
- Message changes.
> Improvement to searchDali 

- prody/dynamics/compare.py
- prody/dynamics/plotting.py
The problem is the indexing was going back to the original model even though I had indexed it already.
> bug fixes for reordered modesets

- prody/proteins/starfile.py
STAR files are metadata files from cryo-EM programs, especially RELION. Some of these files contain information about 2D projection images stored in .mrcs image stack files along other information like their orientations with respect to a 3D model. This function reads this information and uses it to parse 2D images into a numpy array.
>  added function parseImagesFromSTAR 

- prody/chromatin/functions.py
- prody/dynamics/exanm.py
- prody/dynamics/functions.py
- prody/dynamics/plotting.py
- More robust and faster membrane creations;
- Bug fixes to chromatin module.
> Fixes to exANM and Chromatin module

- prody/dynamics/exanm.py
For a system which spent 40s to build a membrane now it only needs 2s.
> Greatly enhanced membrane creation speed

- prody/dynamics/exanm.py
- Implemented convex hull to detect the interior of the protein, so no membrane nodes will be added inside channels, for example. However, it is problematic for dimers, so there is an option `hull` to turn it off.
- Critical bug fixed. The bug will result in wrong results.
> Implemented convex hull and bug fix to exANM

- prody/chromatin/hic.py
- prody/chromatin/straw.py
I only added the straw module and a function called "parseHiCBinary" to read binary Hi-C files. The function may need some modifications in its parameter set. For now, users are able to pass arguments to straw function via kwargs.
> Added a function to read binary hic files

- prody/chromatin/cluster.py
I wrote wrapper functions for the corresponding functions from sklearn.
> Added Gaussian mixture models and Bayesian mixture models to clustering.py in chromatin module

- prody/dynamics/plotting.py
... so that users can specify the color for each domain
> Added a color option to showDomainBar 

- prody/chromatin/functions.py
- prody/chromatin/hic.py
- prody/chromatin/straw.py
- prody/dynamics/analysis.py
- prody/dynamics/plotting.py
- prody/dynamics/signature.py
- prody/ensemble/functions.py
- prody/measure/transform.py
- prody/proteins/compare.py
- prody/proteins/header.py
- prody/utilities/misctools.py
This patch contains fixes to the Chromatin, Ensemble, and SignDy functions.
- Now each `ModeSet` in `ModeEnsemble` has a `matched` indicator to show whether the modes are matched or not.
- `RefineEnsemble` has an additional `protected` argument to take a list of conformations (index or label) to be retained in the refined ensemble.
- Bug fixes and improvements to the Chromatin module.
> Multiple fixes

- prody/measure/transform.py
- prody/utilities/misctools.py
- employ checkWeights in calcTransform and calcRMSD to allow a more flexible weights argument.
- a small fix to rangeString.
> Several fixes

- prody/database/dali.py
- prody/dynamics/compare.py
- prody/dynamics/plotting.py
- prody/ensemble/functions.py
- prody/proteins/compare.py
I decided to separate my branches and this pull request from the commits about building biomolecular assemblies because we still need to check that what I did there is right.
> A few minor bug fixes

- prody/dynamics/compare.py
I accidentally changed my branches around so I now have this branch with this change instead.
> added calcSquareInnerProduct

- prody/dynamics/compare.py
> Revert "added calcSquareInnerProduct"

- prody/dynamics/compare.py
Reverts prody/ProDy#826
I accidentally merged pull request #824 so I reverted it, which created #826. I then merged that revert and reverted it here, which should be the same as having the original pull request.
> Revert "Revert "added calcSquareInnerProduct""

- prody/proteins/compare.py
Otherwise there is one dimension too many in the output.
> Bug fixes to mapChainByChain

- .travis.yml
- prody/database/__init__.py
- prody/database/goa.py
There are still some problems but it largely works. 
The notebook showing usage, example results and problems is at https://pitt.box.com/s/t4gooijqhsotmpo3mtrt2ps3bpdkhxll. HTML output for easier visualising is at https://pitt.box.com/s/a0p9j06u8sf1ytbub7ete4c5u2v4pbo2
> Development of go association database handling

- prody/dynamics/plotting.py
- prody/proteins/functions.py
- prody/utilities/catchall.py
> Color coded square fluctuations 

- prody/sequence/msafile.py
Otherwise it complains that types is not a list of strings
>  bug fix on writePIR 

- prody/dynamics/anm.py
- prody/dynamics/gnm.py
With shift 6, we get one mode too many.
> bug fix for shifts in ANM and consistency fix in GNM

- prody/dynamics/signature.py
- prody/proteins/localpdb.py
We still need to further test the http/ftp things in fetchPDB
>  trying to fix tp=http problem in localpdb

- prody/utilities/misctools.py
Should fix the problem in #856.
> Fixes for a bug in the interactive plots

- prody/dynamics/compare.py
- prody/dynamics/functions.py
- prody/dynamics/mode.py
- prody/dynamics/modeset.py
- prody/ensemble/functions.py
- prody/measure/measure.py
- prody/proteins/compare.py
- prody/utilities/misctools.py
> Added numEntries to NMA, Mode, and ModeSet objects

- prody/proteins/compare.py
Without this fix it gives an error that Sequence objects cannot be indexed.
> bug fix for getAlignedMapping

- prody/proteins/blastpdb.py
- prody/sequence/analysis.py
I have recently realised that there is another function to do this and we may want to unify them. I don't know what the other one does exactly. I do know it has different default alignment parameters and we may want to work out why.
>  added documentation to alignTwoSequencesWithBiopython 

- prody/dynamics/gnm.py
- prody/dynamics/mode.py
- prody/dynamics/modeset.py
This allows the user to provide atoms and get resnums back instead of node indices.
> added atoms as kwargs into getHinges

- prody/apps/apptools.py
I spotted this because of issues #772 and #773
> fixed error message in apps to point to github not bitbucket

- prody/dynamics/plotting.py
I don't know why it was like that but it had an extra row and column of zeros that didn't get filled and it made it not compatible with showing atom information.
> updates to matrix plotting functions

- prody/dynamics/functions.py
This should fix #891. #892 remains a problem
> bug fix to loadModel to account for string type in Atomgroups

- prody/sequence/msafile.py
Previously it would only get the format from the filename extension.
> made kwarg format in parseMSA work

- prody/dynamics/functions.py
Loading them causes problems and they only got saved into there for a short period anyway.
> don't load _combined and _membrane in loadModel

- prody/dynamics/functions.py
>  bug fix for python 2 loadModel 

- prody/sequence/analysis.py
Otherwise the indices are too long.
> fix to alignSequenceToMSA

- prody/measure/transform.py
This fix was suggested in issue #910
> fix to calcTransformation to correctly handle reflection

- prody/measure/transform.py
> A quick fix to the previous fix to the calcTransform function

- prody/sequence/analysis.py
Otherwise, it complains about an unfilled positional argument.
> bug fixes to alignSequenceToMSA

- PKG-INFO
- prody/dynamics/gnm.py
- prody/dynamics/nma.py
- prody/utilities/catchall.py
- Changed the `n_atoms` checker in `NMA.setEigens` from raising an error to a warning.
- Made sure the ticks for `showMatrix` are integers.
> Some minor fixes

- prody/ensemble/functions.py
- prody/proteins/compare.py
- prody/utilities/__init__.py
- prody/utilities/laptools.py
- prody/utilities/logger.py
- prody/utilities/misctools.py
+ Implemented a generalized version of the linear assignment algorithm that allows multiple assignments and *k*-best solutions.
+ Implemented the selection of `AtomMap` instances based on superposition onto the full reference structure.
- Because of the enormous search space, `O(n!/(m-n)!)`, the algorithm searches greedily for solutions, i.e. it may not find the global optimum.
> Implemetation of auto-matching for multimers

- prody/proteins/pdbclusters.py
This enables one to obtain some statistics on PDB clusters without knowing representative PDB IDs.
> preprocess pdbclusters upon loading

- prody/atomic/pointer.py
> Added iterBonds for AtomPointer classes

- prody/proteins/compare.py
- `mapping='auto'` will map the structure sequentially first and then structurally if the former didn't work.
- Fixed bug where `combineAtomMaps` could go in infinite loops.
- CEalign and predefined mapping will completely ignore the `seqid` cutoff.
> Added an 'auto' option to mapChainOntoChain

- prody/proteins/localpdb.py
> fixed an error in fetchPDB documentation

- prody/database/pfam.py
- prody/proteins/functions.py
> added error for not having tsv results from hmmscan for searchPfam

- prody/proteins/functions.py
- prody/utilities/catchall.py
It's not really necessary but could be helpful to users who don't know Biopython well.
> added writeTree as a wrapper for Phylo.write

- prody/dynamics/plotting.py
- prody/utilities/catchall.py
needed to show PRS heatmap with hierarchical clustering dendrograms, so I edited showMatrix function.  if both x_array and y_array are given, user can ask row or column clustering using cluster_row/cluster_col kwargs. generates following output.
> added hierarchical clustering functionality to showMatrix

- prody/database/__init__.py
- prody/database/emsurfer.py
- prody/proteins/emdfile.py
I think this should be accessible for checking.
> added emsurfer file for using EM-Surfer server

- prody/proteins/emdfile.py
> bug fix to emdfile

- prody/dynamics/plotting.py
We may still have a problem with c not conforming to pyplot's options because of the checks we're doing but this is an improvement.
> bug fix to remove user-specified c kwarg in showProjection

- prody/dynamics/analysis.py
- prody/dynamics/plotting.py
This should help with issue #1012
> updated documentation for showCrossProjection and calcCrossProjection

- prody/dynamics/analysis.py
This addresses problem to 2 from #1003
> standardised calcProjection to match showProjection with norm=False

- prody/ensemble/ensemble.py
This is based on getRMSDs and it works well.
> added getDefvecs to Ensemble

- prody/database/dali.py
These functions allow us to filter multimers to only include chains with dali mappings. There is also an option to select multimers with a particular number of chains.
> added daliFilterMultimer and daliFilterMultimers

- prody/proteins/pdbfile.py
Otherwise, we get an error from setBonds and can't parse the PDB.
> warning and not parsing CONECT records when incompatible with subset

- prody/dynamics/signature.py
Maybe we should check they're really unneeded.
> cleaned up unneeded variables in SignDy

- prody/dynamics/compare.py
- prody/dynamics/plotting.py
This allows things like the following:
```showOverlapTable(pca, anm_ens[:,:20].getEigvecs().mean())```
> added ndarrays to calcOverlap and showOverlapTable

- prody/proteins/ciffile.py
This is the actual fix for #1038
> bug fix to chain parsing for ciffile

- prody/dynamics/pca.py
This is a problem we realised because of #1042
> made PCA setCovariance set _n_atoms as int

- prody/dynamics/compare.py
- prody/dynamics/signature.py
That way we can have a matrix.
> added diag kwarg option to showSignatureOverlaps

- prody/dynamics/signature.py
I decided to separate out this part, which definitely works.
> fix for calcSignatureFractVariance with 1 mode

- prody/database/dali.py
- prody/database/emsurfer.py
- prody/proteins/blastpdb.py
I previously made a feature request for this (#882) and now I think I've done it.
> making PDBBlastRecord have getRecord() like DaliRecord

- prody/dynamics/signature.py
I checked and this the only time it's used so it should be safe to change.
> clearer variable name coordsets with s

- prody/proteins/emdfile.py
The documentation was wrong, the make_nodes parameter was unnecessary, and the `_parseEMDLines`/`parseEMDStream` pair was a debugging nightmare. Now this should be better.
> Tidying up emdmap code

- prody/atomic/fields.py
- prody/atomic/functions.py
- prody/dynamics/__init__.py
- prody/dynamics/analysis.py
- prody/dynamics/entropy.py
- prody/dynamics/functions.py
- prody/dynamics/imanm.py
- prody/dynamics/perturb.py
- prody/dynamics/signature.py
- prody/dynamics/vmdfile.py
- prody/ensemble/functions.py
- prody/utilities/misctools.py
The most significant thing I did was moved DTYPE from atomic fields to misctools
> some tidying up

- prody/apps/apptools.py
- prody/dynamics/bbenm.py
bbenm had a completely wrong header. apptools just had a small grammatical thing.
> fixed headers for bbenm and apptools

- prody/measure/contacts.py
There was an incomplete sentence before that didn't make sense.
> contacts docs fix

- CONTRIBUTING.md
- prody/apps/apptools.py
- prody/atomic/fields.py
- prody/atomic/functions.py
- prody/database/goa.py
- prody/dynamics/__init__.py
- prody/dynamics/analysis.py
- prody/dynamics/bbenm.py
- prody/dynamics/entropy.py
- prody/dynamics/functions.py
- prody/dynamics/imanm.py
- prody/dynamics/perturb.py
- prody/dynamics/plotting.py
- prody/dynamics/rtb.py
- prody/dynamics/signature.py
- prody/dynamics/vmdfile.py
- prody/ensemble/functions.py
- prody/ensemble/pdbensemble.py
- prody/proteins/__init__.py
- prody/proteins/blastUniProtKB.py
- prody/proteins/ciffile.py
- prody/proteins/emdfile.py
- prody/proteins/pdbfile.py
- prody/utilities/catchall.py
- prody/utilities/misctools.py
This is based on a method that conformations have.
> added getTransformations to pdbensemble

- prody/proteins/pdbligands.py
I'm sure PDBLigandRecord could do with more methods but that should do for now.
> added PDBLigandRecord, parsePDBLigand and calc2DSimilarity

- prody/ensemble/functions.py
- prody/ensemble/pdbensemble.py
> added selstrs to PDBEnsemble

- prody/sequence/analysis.py
There was documentation for a chain argument but no such argument.
> kwargs fix to alignSequenceToMSA

- prody/dynamics/plotting.py
This fixes a minor inconsistency of labelling.
> showProj axes label fix

- prody/dynamics/plotting.py
Again, a very minor change, which doesn't really do anything.
> showProj line formatting fix

- prody/dynamics/plotting.py
> showProj hist axes label fix

- prody/tests/dynamics/test_pca.py
We previously had an issue with this so now we check for it and hopefully it passes.
> added pca n_modes checks

- prody/apps/prody_apps/prody_blast.py
- prody/proteins/blastpdb.py
- prody/sequence/msafile.py
Before this, it had problems handling filename or xml input.
> Blast pdb fixes

- prody/proteins/header.py
- prody/proteins/pdbfile.py
This makes users more aware of the outcomes.
> improved biomol docs

- prody/atomic/atomgroup.py
This is a first go at addressing https://github.com/prody/ProDy/issues/798
> added inferBonds to AtomGroup

- prody/proteins/pdbclusters.py
This allows it to support multiple sequence identities for fetching at once.
> Pdbclusters fix

- PKG-INFO
- setup.py
Made it so that the authors are ordered from most recent to least recent main developers and changed the email to mine as the only remaining one.
> updated author info

- prody/ensemble/functions.py
Otherwise, we have a problem with an undefined variable `i`.
> fix to protected in refineEnsemble

- prody/database/cath.py
- prody/database/pfam.py
- prody/database/uniprot.py
- prody/dynamics/heatmapper.py
- prody/proteins/dssp.py
I have added docs for CATH in line with #1124, fixed a minor bug there, and made some minor docs updates to other files.
> docs_updates

- prody/dynamics/nmdfile.py
Previously, parseNMD could not handle the case where segnames were '' and the warnings were wrong. It would say that the label chainids was found more than once, which wasn't right. The next error down about number of expected values vs parsed ones was also wrong.
> parseNMD fixes

- prody/atomic/atomgroup.py
- prody/atomic/bond.py
- prody/atomic/fields.py
- prody/atomic/pointer.py
- prody/atomic/select.py
This helps users know about this new method.
> added inferBonds info

- prody/proteins/ciffile.py
- prody/proteins/starfile.py
- prody/utilities/misctools.py
This adds initial functionality in response to #1160. It allows us to parse the mmCIF header into a StarDict. We still need to map field keys to create Chemicals, Polymers, DBRefs, etc.
> Added mmcif header parsing

- prody/proteins/ciffile.py
- prody/proteins/starfile.py
1. Fixed the specification of which lines to include as 'header'
2. Fixed a bug in parseSTARLines where incorrect indexing of StarDataBlock entries led to overwriting of entries
> mmCIF header parsing fixes

- prody/proteins/compare.py
> buildPDBensemble fix

- prody/proteins/starfile.py
This just makes things clearer for the user.
> import fix for parseImagesFromSTAR

- prody/atomic/atomgroup.py
- prody/dynamics/exanm.py
1. changed dot product to matmul in exanm for python 2 compatibility
2. fixed atomgroup merging issue
> exanm update and bug fixes

- prody/sequence/analysis.py
> improved alignSequenceToMSA

- prody/proteins/compare.py
I have reverted some differences from v1.10.11 because seqid and getDictMapping weren't working properly. I also found one for coverage to get back the same behaviour as before.
> Mapping fixes

- prody/atomic/hierview.py
- prody/database/dali.py
- prody/dynamics/plotting.py
I haven't yet made the commit for the version number change as I want that to come last.
> Final changes before making release v1.11

- PKG-INFO
- prody/__init__.py
- setup.py
> added scipy to dependencies

- pyproject.toml
It was already added elsewhere
> added scipy to pyproject.toml

- prody/apps/evol_apps/evol_conserv.py
- prody/sequence/msa.py
- prody/sequence/plotting.py
- prody/sequence/sequence.py
Otherwise the label start and end don't match the MSA anymore and pickSequence and getResnums have problems.
> made refineMSA update label after structure refinement

- INSTALL.rst
This now adds instructions about conda/Anaconda, which will be updated onto the website
> updated INSTALL docs

- INSTALL.rst
- docs/docs
- docs/release/index.rst
> Docs update

- prody/dynamics/exanm.py
This brings back the original code for python 2 but leaves in the improved code for python 3.
> exanm py2 fix

- docs/devel/website.rst
This is a first draft guide of how to build the website
> added website building docs

- prody/proteins/pdbfile.py
> merge alternating chids

- prody/proteins/pdbfile.py
> Revert "merge alternating chids"

- prody/dynamics/__init__.py
- prody/dynamics/exgnm.py
This is a first attempt to close #899 and it looks pretty good:
```
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)]
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.
In [2]: kg2 = parsePDB('C:/Users/james/Box/james-and-greger-lab/PBP_pdbs/iGluR/ampar/whole/3kg2-opm.pdb', subset='ca')
@> 3116 atoms and 1 coordinate set(s) were parsed in 0.07s.
In [3]: gnm = GNM()
In [4]: gnm.buildKirchhoff(kg2)
@> Kirchhoff was built in 0.11s.
In [5]: gnm.calcModes()
@> 20 modes were calculated in 1.54s.
In [6]: exgnm = exGNM()
In [7]: exgnm.buildKirchhoff(kg2)
@> Membrane was built in  4s.
@> layers: [0 1]
@> max layer: 1
@> layer: 0
@> layer: 1 …
```
> added exgnm

- prody/proteins/pdbfile.py
> added TER line writing

- prody/database/dali.py
- prody/dynamics/analysis.py
> docs fixes

- prody/database/__init__.py
- prody/database/dali.py
- prody/database/quartataweb.py
This can now navigate QuartataWeb. Downloading and parsing the results comes next.
> added QuartataWebBrowser

- prody/database/quartataweb.py
- prody/proteins/pdbfile.py
This fixes a bug if the pdbter flag is not set and some more with importing quartata (#1214).
> Pdbter and quartata fixes

- prody/ensemble/functions.py
- prody/ensemble/pdbensemble.py
- prody/proteins/compare.py
This was noticed because of another bug where the selstr is being filled with labels, which I have also fixed.
> added selstrs to loadEnsemble and saveEnsemble

- prody/compounds/bird.py
- prody/compounds/ccd.py
- prody/proteins/starfile.py
Without these changes, there were many errors and unexpected results.
> starfile searching and indexing fixes

- prody/proteins/ciffile.py
- prody/proteins/starfile.py
It could be useful for later. One place in particular where it could help is distinguishing sections pre and post the atomic one for writing mmCIF files.
> used orderedDict for cif/star parsing/init

- docs/reference/domain_decomposition/index.rst
- prody/database/__init__.py
- prody/database/goa.py
- prody/database/pfam.py
- prody/database/uniprot.py
- prody/dynamics/__init__.py
- prody/dynamics/plotting.py
- prody/proteins/__init__.py
- prody/proteins/ciffile.py
- prody/proteins/emdfile.py
> Docs and fixes for ProDy 2.0

- docs/reference/compounds/bird.rst
- docs/reference/compounds/ccd.rst
- docs/reference/database/quartata.rst
- docs/reference/dynamics/exgnm.rst
- docs/reference/index.rst
- docs/release/index.rst
Should end up with docs working
> fixed too short underline and not in toc warnings

- docs/devel/website.rst
- prody/compounds/__init__.py
- prody/database/__init__.py
> Docs and fixes

- prody/dynamics/adaptive.py
There is now no dependence on trimming or slicing or selections.
> cleaned up adaptiveANM

- prody/dynamics/essa.py
> Minor revision to ESSA.

- prody/dynamics/essa.py
Bug in saveEigvals method in ESSA is fixed.
> Bug in saveEigvals method in ESSA is fixed.

- prody/dynamics/adaptive.py
Now aANM code should reproduce the results in the paper.
> Major fixes to aANM

- prody/ensemble/ensemble.py
Otherwise it only worked for PDBEnsemble
> fixed Ensemble getDefvecs

- prody/dynamics/essa.py
Just a cosmetic grammatical fix.
> close bracket for Fpocket warning

- prody/proteins/pdbfile.py
Also fixed bug with anisou writing when anisous is None.
> Added charges to writePDB

- prody/apps/prody_apps/prody_anm.py
- prody/apps/prody_apps/prody_gnm.py
> fixed extensions for b-fac from apps

- docs/about/people.rst
We may want to update this further but for now this is a start.
> updated Burak contribution

- prody/proteins/ciffile.py
- prody/proteins/emdfile.py
- prody/proteins/pdbfile.py
- prody/proteins/wwpdb.py
- prody/utilities/misctools.py
> 5 letter emd

- prody/dynamics/analysis.py
> extended anisous to take mode

- prody/database/pfam.py
Otherwise this causes problems when both the accession and id don't work (see #1295).
> pfam fixes for 4nq8

- prody/dynamics/anm.py
- prody/dynamics/gnm.py
- prody/dynamics/pca.py
- prody/dynamics/signature.py
Just a grammatical fix to logging number of modes calculated so we don't get "1 modes were calculated"
> logger fix for 1 mode

- prody/proteins/pdbfile.py
> parsePDB hex resnums

- prody/dynamics/nmdfile.py
This is a functionality that most of the save and write functions have but writeNMD doesn't so I'm adding it.
> added extension to writeNMD

- prody/dynamics/gnm.py
> gnm_bug_fix

- prody/dynamics/nmdfile.py
> parseNMD fix

- prody/proteins/localpdb.py
This is what I originally intended for this function, but I didn't get there.
> fetchPDBs actually fetches multiple files

- prody/dynamics/nmdfile.py
> parseNMD fix 2

- prody/dynamics/pca.py
Fixes a bug introduced in #1310 similar to #1324
> pca bug fix

- prody/proteins/pdbfile.py
> parsePDB accept dict

- prody/dynamics/mechstiff.py
> added KMR17 ref

- prody/atomic/hierview.py
> hierview doc fix

- .github/workflows/main.yml
This is a first draft based on https://github.com/I2PC/xmipp/blob/devel/.github/workflows/main.yml
> added simple github actions test

- prody/proteins/pdbfile.py
> parsePDB_bonds_fix

- prody/proteins/ciffile.py
> mmCIF nModels fix

- prody/atomic/select.py
> select deprec fix

- prody/atomic/bond.py
> Bond doc fix

- prody/dynamics/compare.py
- adds calcRWSIP for root weighted square inner product from Carnevale et al. 2007
- adds calcRMSIP, which is an alias for calcSubspaceOverlap
- fixes reference formatting on calcSquareInnerProduct
- adds calcSIP, which is an alias for calcSquareInnerProduct
> added calcRWSIP function and calcRMSIP and calcSIP aliases

- prody/proteins/pdbfile.py
> altloc all option

- docs/release/v2.0_series.rst
I think we should be ready to make the release now
> V2.0.1 release changes

- prody/proteins/starfile.py
numDataBlocks, numLoops, etc. become functions like in the rest of ProDy protecting private properties _n_data_blocks, _n_loops, etc.
> style fixes for starfile

- prody/dynamics/functions.py
I've just made a function that should rotate modes onto a new coordinate frame by alignment to another structure. 
Essentially what it does is the following:
1. Add the mode vectors to the original reference structure (atoms) to get new structures that can be aligned onto a target reference structure (ref)
2. Use a PDBEnsemble object to align this set of new structures onto *ref*
3. Subtract the aligned *atoms* from the aligned new structures to get mode vectors again, which are now aligned differently, and put them in a new object of the same type with the original eigenvalues
I have tested it with 1ake_A and 4ake_A as well as 3h5v_A and 3hsy_B. For the latter case, the results are as follows:
```
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:40:17) 
Type 'copyright', …
```
> added realignModes

- prody/dynamics/functions.py
> add missing import alignChains

- prody/dynamics/functions.py
New function to parse modes from gromacs covar (PCA) or nmaeig (NMA).
> Gromacs parser

- prody/dynamics/essa.py
ESSA __init__ had `self._lig = None` twice so I've removed one
> del redundant ESSA _lig

- prody/dynamics/signature.py
- pop kwargs and pass others to show functions
- normalize overlap matrix between 0 and 1
> showSignatureOverlaps improvements

- docs/release/v2.0_series.rst
- prody/__init__.py
I may update this more or this may be it. We'll see.
> Final release changes

- .github/workflows/main.yml
Hopefully this will let it trigger whenever there's a push or pull request. The previous version didn't because of the branch specification. 
I can already see it responding to pushes on my fork with the meaningless change of an extra # in a comment.
> Github actions improvement

- prody/dynamics/compare.py
- prody/dynamics/signature.py
some minor things I picked up looking at the match modes turbo option
> Match turbo

- prody/atomic/functions.py
This allows us to limit the size of RTB blocks, which can otherwise get quite large, especially when using secondary structures.
For example, without this option, 4ake chain A can have very big blocks:
```
In [3]: b, am = prody.assignBlocks(atoms, secstr=True)
In [4]: rtb = prody.RTB()
In [5]: rtb.buildHessian(am, b)
@> Hessian was built in 0.06s.
@> System has 28 blocks, the largest with 27 of 214 units.
@> Block Hessian and projection matrix were calculated in 0.03s.
```
With this option, this can be much better:
```
In [6]: b, am = prody.assignBlocks(atoms, secstr=True, max_size=10)
In [7]: rtb.buildHessian(am, b)
@> Hessian was built in 0.07s.
@> System has 39 blocks, the largest with 9 of 214 units.
@> Block Hessian and projection matrix were calculated in 0.05s.
```
This also gives …
> added max block size

- prody/proteins/functions.py
> View3D docs

- prody/proteins/compare.py
This wasn't actually an appropriate fix to #1483 as discussed there. The better way to do it is to have the user use protein atoms in the input to matchAlign
> Revert #1484

- prody/dynamics/analysis.py
> calcPairDeformationDist docs fix

- prody/dynamics/sampling.py
Just some minor things I spotted that shouldn't affect anything.
> traverseModes docs fixes

- INSTALL.rst
- docs/conf.py
also added MDTraj, which we now use for parseGromacsModes
> fix mdanalysis broken link

- docs/_theme/howtocite.html
- docs/about/citing.rst
- prody/apps/apptools.py
Added it to all the places I think
> Cite ProDy 2

- prody/apps/prody_apps/prody_anm.py
- prody/apps/prody_apps/prody_gnm.py
- prody/apps/prody_apps/prody_pca.py
- prody/apps/prody_apps/prody_select.py
Extends select, pca, anm and gnm app functionality to include altloc selection as well as zero mode selection for the last two.
> apps altloc and zeros

- prody/apps/prody_apps/prody_gnm.py
This was somehow missed from copying something
> gnm app altloc fix

- prody/atomic/functions.py
- prody/measure/measure.py
Added functionality to assignBlocks to cut blocks based on distance as before that it was completely sequential with a C-terminus connecting to the next N-terminus and other large gaps being ignored too. 
This required moving it to measure to use calcDistanceMatrix and calcDistance.
> assignBlocks dist cutoff

- prody/dynamics/plotting.py
> add norm to showCrossCorr

- prody/apps/prody_apps/nmaoptions.py
- prody/apps/prody_apps/prody_anm.py
- prody/apps/prody_apps/prody_gnm.py
- prody/apps/prody_apps/prody_pca.py
- prody/dynamics/functions.py
- prody/proteins/starfile.py
These changes allow us to interface with the Scipion SetOfNormalModes object in the ProDy API and apps
> parse and write Scipion ContinuousFlex modes

- prody/dynamics/analysis.py
Added Scipion score for normal modes from HEMNMA, which prioritises them based on mode number and collectivity
> Scipion HEMNMA Score

- PKG-INFO
- docs/release/v2.0_series.rst
- prody/__init__.py
I have added quite a lot recently so I think it's time to make another release. Here is a draft of the release notes.
> release prep for v2.1.0

- prody/database/pfam.py
I accidentally messed up the master branch and #1527 got removed so here it is again.
> Parse pfam pdbs fix

- PKG-INFO
- docs/release/v2.0_series.rst
- docs/release/v2.1_series.rst
- prody/__init__.py
- bump version
- add release notes
> Release prep for v2.1.1

- prody/dynamics/plotting.py
Fixed overlay options for multiple chains.
> ShowAtomicLines is fixed for multiple chains

- PKG-INFO
- docs/release/v2.1_series.rst
- prody/__init__.py
Making release of v2.1.2 as we have quite a critical fix.
> bump version and release note v2.1.2

- prody/dynamics/functions.py
- prody/proteins/starfile.py
- parseScipionModes can now read sqlite files when xmd files aren't in the specified directory
- parseScipionModes and writeScipionModes can now also handle eigenvalues in sqlite files
> Scipion modes updates to handle eigenvalues and sqlite files

- setup.py
> restrict biopython to 1.76 for python 3 too

- prody/apps/prody_apps/prody_pca.py
This should maintain efficiency of using SVD when not specifying number of processors
> Restore SVD in some cases

- prody/dynamics/functions.py
Parsing from a directory doesn't always work e.g. after making a subset. Parsing from a metadata file should be more robust.
> parseScipionModes from metadata file

- prody/atomic/flags.py
> mn added to doc

- prody/proteins/ciffile.py
> Fixes #1568. Added check around parsing of pdbx_PDB_ins_code

- prody/utilities/misctools.py
shlex is a built-in module so we don't need an import check
> clean up shlex split

- prody/atomic/flags.py
> fixed updateDefinitions

- prody/dynamics/perturb.py
I'm not sure why this option was removed but it's still useful
> restore matrix option to dfi and dci

- .github/workflows/main.yml
- docs/conf.py
- prody/database/pfam.py
- prody/tests/database/test_pfam.py
> pfam to pfam-legacy

- prody/atomic/fields.py
- prody/tests/datafiles/__init__.py
- prody/tests/proteins/test_ciffile.py
> chid to 6 char

- prody/proteins/compare.py
- prody/sequence/analysis.py
- prody/tests/database/test_pfam.py
It was treating these indices as if they were residue numbers without taking into account that residue numbers have gaps. Now it works fine
> fixes for selecting by aligning to msa

- docs/release/v2.3_series.rst
- prody/__init__.py
- pyproject.toml
> pre-release v2.3.1

- prody/measure/measure.py
Each row of the output matrix is now a column of the eigenvector matrix of the inertia tensor as in the definition
> transpose princ axes matrix to get columns

- prody/atomic/flags.py
- prody/atomic/selection.py
- prody/proteins/ciffile.py
- prody/proteins/pdbfile.py
> new flag selpdbter to keep ter lines in selections

- setup.py
> add cif datafiles to setup

- prody/apps/prody_apps/prody_select.py
Make the help reflect the actual behaviour
> Select app help fix

- prody/database/dali.py
Proposed changes to address #1637 
Adds a flag to filter that makes cutoffs behave consistently. Defaults maintain old behavior.
> Addresses inconsistent cutoffs in filtering

- prody/trajectory/psffile.py
Maybe their tutorial got updated but now the psf format page is 2 pages later than what we have
> fix psf tutorial link

- prody/apps/prody_apps/prody_anm.py
- prody/apps/prody_apps/prody_gnm.py
- prody/apps/prody_apps/prody_pca.py
> show matrix interactive false

- prody/dynamics/plotting.py
- prody/utilities/catchall.py
> reset interactive to false for matplotlib 3.6

- prody/ensemble/functions.py
address #1640 
The code works as follows:
```
In [2]: from prody.tests.datafiles import *
In [3]: ag = parsePDB("mdm2.pdb")
@> 1449 atoms and 1 coordinate set(s) were parsed in 0.02s.
In [4]: ens = parseDCD("mdm2.dcd")
@> DCD file contains 500 coordinate sets for 1449 atoms.
@> DCD file was parsed in 0.03 seconds.
@> 8.33 MB parsed at input rate 240.50 MB/s.
@> 500 coordinate sets parsed at input rate 14436 frame/s.
In [5]: ens_ref = refineEnsemble(ens, lower=1.0)
@> Ensemble was refined in 11.06s.
@> 1 conformations were removed from ensemble.
In [6]: ens_ref = refineEnsemble(ens, lower=1.0, data_type="seqid") …
```
> refineEnsemble seqid data type

- prody/dynamics/plotting.py
closes #1553 
We can now make plots like the following:
```
prody.showProjection(ens, pca[:2], density=True)
```
```
prody.showProjection(ens, pca[:2], density=True, levels=30, cmap=plt.cm.Reds)
```
```
prody.showProjection(ens, pca[:2], density=True, levels=30, cmap=plt.cm.Reds, fill=True)
```
> added sns kde

- prody/proteins/__init__.py
- prody/proteins/fixer.py
This is useful already as a feature independently of the interactions analysis, so I have put it in its own module and copied it to its own pull request to merge earlier
> taken addMissingAtoms from interactions

- prody/dynamics/plotting.py
Otherwise get an error about show_density not defined
Also, fixed docs a little
> show_density false for 3d proj

- prody/dynamics/plotting.py
> turn off adjust_text for 3d

- prody/proteins/blastpdb.py
> updated blastpdb split

- prody/atomic/functions.py
- prody/tests/atomic/test_atomic.py
> fix saveAtoms ending

- prody/proteins/ciffile.py
- prody/proteins/cifheader.py
> Support PDB-REDO cif

- prody/utilities/catchall.py
Before, it was set to 0. instead
> actually use vcenter in showMatrix

- prody/apps/prody_apps/prody_energy.py
more consistent with others and more informative
> better prody energy help

- .github/workflows/main.yml
We use some version of setup-python that someone made to fix the issue
> Fix github actions for py27

- prody/atomic/select.py
> add segname to select evalmap

- prody/apps/prody_apps/prody_energy.py
boxSize is new, padding was missing something
> add boxSize and fix padding to energy app

- prody/dynamics/plotting.py
With lots of structures, adjustText is slow and doesn't really work
> no adjustText for many structs

- prody/proteins/waterbridges.py
@fdoljanin @karolamik13, this fixes the problem I commented on
> fix water bridges plt import

- prody/proteins/pdbfile.py
- prody/tests/datafiles/__init__.py
- prody/tests/proteins/test_pdbfile.py
This is the format that TER lines actually have in pdb files (https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#TER) and also the END lines (https://www.wwpdb.org/documentation/file-format-content/format33/sect11.html#END)
Modeller was complaining about these before
> fix TER lines

- PKG-INFO
- docs/apps/prody/prody.txt
- docs/reference/apps/prody_clustenm.rst
- docs/release/v2.4_series.rst
- prody/__init__.py
- prody/apps/prody_apps/__init__.py
- prody/apps/prody_apps/nmaoptions.py
- prody/apps/prody_apps/prody_anm.py
- prody/apps/prody_apps/prody_clustenm.py
- prody/apps/prody_apps/prody_gnm.py
- prody/apps/prody_apps/prody_pca.py
- prody/dynamics/anm.py
- prody/dynamics/clustenm.py
- prody/dynamics/gnm.py
- prody/dynamics/pca.py
- prody/utilities/eigtools.py
This app can run ClustENM and save the outputs in pdb and ens.npz files. 
Example command:
```
prody clustenm Runs/000002_ProDySelect/4ake_atoms.pdb --ngens 2 --number-of-modes 3 --nconfs 5 --rmsd 1. -c 15.0 -g 1.0 --maxclust "(2, 3)" --threshold "None" --solvent imp --force_field None --ionicStrength 0.0 --padding 1.0 --temp 303.15 --t_steps_i 1000 --t_steps_g 7500 --tolerance 10.0 --maxIterations 0 -P 6 -o Runs/000089_ProDyClustENM/clustenm_1 --file-prefix pdbs --no-sim --turbo --outlier --mzscore 3.5
```
Outputs:
```
(scipion3) jkrieger@whipple ~/ScipionUserData/projects/TestProDyClustENM $ ls -ltrah Runs/000089_ProDyClustENM/clustenm_1/
total 1.2M
drwxr-xr-x 2 jkrieger jkrieger 4.0K Aug  9 16:37 pdbs
-rw-r--r-- 1 jkrieger jkrieger 1.2M Aug  9 16:37 pdbs.ens.npz
drwxr-xr-x 3 jkrieger …
```
> Clustenm app

- prody/proteins/pdbfile.py
> fix end and endmdl

- prody/sequence/analysis.py
the other program method part had a bug and I've changed the default method to biopython local
> fix buildMSA

- prody/database/cath.py
- prody/tests/database/test_cath.py
> fix getchildren deprecation

- prody/proteins/pdbfile.py
Also, better documentation and warnings in parsePDB
> fix writePDB for long resnames

- docs/devel/develop.rst
I just spotted something that wasn't quite right
> fix develop docs

- prody/dynamics/analysis.py
Fix multiprocessing issue mentioned in #1749
> fix: calcCrossCorr multiprocessing issue #1749

- prody/proteins/waterbridges.py
Fixed bug where calcWaterBridgesStatistics returns the same residue pair twice, but in a different order.
This doesn't happen for info output nor log anymore but is still a feature of 'indices' because e.g. calcWaterBridgeMatrix probably shouldn't care about symmetry.
> Fixed duplicates in calcWaterBridgesStatistics

- prody/proteins/waterbridges.py
just made the plotting more like other prody plotting a bit
> separate show funcs for watfinder

- README.rst
- prody/proteins/interactions.py
I added information about the hpb code in README and in docx.
> Interactions (additional description)

- prody/proteins/ciffile.py
- prody/proteins/pdbfile.py
> fix altloc docs

- prody/proteins/ciffile.py
chain goes before subset and doesn't get an underscore
> fix mmcif title suffix

- prody/dynamics/functions.py
They were very out of date and uninformative
> fix parseScipionModes docs

- prody/proteins/interactions.py
I added new methods in the protein-ligand interactions class. Some improvements to the previous methods/functions were also added. Now, it was tested on the trajectory with multiple chains and multiple ligands. More information to docx was added and some LOGGER printing was removed.
> Protein-ligand interactions [new functions and further improvements]

- prody/measure/contacts.py
- prody/measure/measure.py
- prody/tests/measure/test_contacts.py
> add seqsep to iterNeighbors

- prody/proteins/interactions.py
contacts_min removed from calcFrequentInteractors() in protein-ligand interactions
> Interactions

- prody/proteins/pdbfile.py
> Options for writePDB TER, REMARK, END lines

- prody/atomic/atomic.py
Without this fix, we can't load old NPZ files from before changing the anisou handling
> fix no attribute _anisous

- prody/measure/measure.py
It must have been accidentally introduced in #1786 and it breaks many functions
> remove undefined var spacing

- prody/utilities/catchall.py
Can use any distance matrix e.g. an RMSD matrix
> add kmedoid clustering

- docs/apps/prody/prody.txt
- prody/apps/prody_apps/prody_anm.py
This mentions NMA under the description of the ANM app
closes #1830
> Update app docs to include NMA

- prody/apps/prody_apps/prody_clustenm.py
- prody/dynamics/clustenm.py
- prody/ensemble/functions.py
I think now it should be there
> more Scipion minimal clustenm changes

- .github/workflows/main.yml
- PKG-INFO
- prody/tests/database/test_pfam.py
- pyproject.toml
- setup.py
> limit pyparsing<=3.1.1

- prody/dynamics/plotting.py
This allows showProjection to be used with an already calculated projection so it doesn't need to be calculated again
> add showProj proj input

- prody/proteins/cifheader.py
> cifheader fixes

- prody/database/pfam.py
- prody/tests/database/test_pfam.py
Otherwise, fetchPfamMSA doesn't work. This is only a hot fix as we still need functionalities for getting other alignments.
> set fetchPfamMSA default to seed

- prody/proteins/waterbridges.py
It said multimodal with an a instead of an e, so I changed that and decided to improve it further
> fix calcWaterBridgesTraj docs

- docs/about/people.rst
I updated the list of the people who are developing ProDy. This list will be used by the ProDy website.
> people update

- pyproject.toml
- setup.py
fixes #1906 for now. We will need to make an actual fix at some point.
> Hot fix: Update pyproject.toml and setup.py for scipy

- prody/dynamics/clustenm.py
- prody/ensemble/functions.py
There's a problem with _cc if it's not defined. 
Then topology and positions don't work for loading because they require openmm. I guess we could add an import though instead
> Fix clustenm saving and loading

- prody/proteins/waterbridges.py
This fixes the problem with the last implementation of calcWaterBridgesTrajectory that didn't actually output the results
> fix multiprocessing output

- docs/release/index.rst
- prody/proteins/waterbridges.py
From segname PROA from CCT, this gives a speed-up of about 3.3x for 10 frames.
Without the fix the time is 163.88 seconds and with the fix the time is 48.96 seconds.
> Parallel savePDBWaterBridgesTrajectory

- CONTRIBUTING.md
- PKG-INFO
- docs/apps/prody/index.rst
- docs/conf.py
- docs/index.rst
- prody/ensemble/functions.py
Previously, I only updated the README. Then I realised that PKG-INFO needed to change too and probably these other files too.
There's one left at https://github.com/prody/ProDy/blob/main/docs/devel/website.rst, which I don't know what to do with.
https://github.com/prody/ProDy/blob/main/docs/devel/website.rst?plain=1#L17
First log in to the ProDy webserver (prody.csb.pitt.edu) then run the following::
https://github.com/prody/ProDy/blob/main/docs/devel/website.rst?plain=1#L37
http://prody.csb.pitt.edu/test_prody/_build/html/ in your web browser.
> update website throughout prody

- .github/workflows/main.yml
- docs/apps/docapps.py
- prody/apps/evol_apps/__init__.py
- prody/apps/prody_apps/__init__.py
- prody/dynamics/rtbtools.c
- prody/tests/dynamics/test_lda.py
- prody/tests/proteins/test_fixer.py
- prody/tests/proteins/test_waterbridges.py
- prody/utilities/doctools.py
- prody/utilities/eigtools.py
- prody/utilities/misctools.py
- pyproject.toml
- scripts/evol
- scripts/prody
- setup.py
fixes #1956 and #1915 
Now prody compiles with the latest numpy!
> Fix rtbtools to permit numpy upgrade

- .github/workflows/main.yml
- prody/tests/database/test_pfam.py
We were making so many requests to pfam that lots of them were failing so hopefully now this is better
> Less tests

- prody/dynamics/anmd.py
- prody/tests/dynamics/test_anmd.py
This is more in line with what users are likely to do
> change ANMD num_steps default to 5

- setup.py
I am keeping the pre-compiled versions for people who still want to do development installs and have systems compatible with them, but it is now checking if there's already a file there first. 
I've also cleaned up some commented parts that don't work.
> Clean up hpb install and copying to install via conda-forge

- prody/proteins/pdbfile.py
- prody/proteins/waterbridges.py
- prody/utilities/misctools.py
This should handle #2053, but probably there are other things that we will need to fix too to migrate to numpy 2. For now, this full request will check if this doesn't break anything in existing numpy versions
> change alltrue to all

- prody/measure/measure.py
This could be helpful for getting sizes of these axes maybe and getting tighter boxes surrounding selections than those aligned to x, y and z.
> add return eigvals to calcPrincAxes

- prody/utilities/catchall.py
> fix matplotlib version check for interaction False

- prody/proteins/cifheader.py
fixes #2060 
Also includes a change of np.where to np.nonzero
> trim paired gaps from unobs

- prody/apps/prody_apps/prody_clustenm.py
> write cc array in clustenm app

- PKG-INFO
- docs/release/v2.6_series.rst
- prody/__init__.py
Making a small version change for the critical CLUSTENM(D) fixes (some other fixes as well).
> prepare for v2.6.1 release

- setup.py
This should make the README.md content appear on pypi when we make our next release there.
> added long description to setup.py
