prody/ProDy

- prody/comd/comd.py
- prody/dynamics/anm.py
- prody/ensemble/functions.py
- prody/proteins/compare.py
- prody/proteins/localpdb.py
1. Corrected a misspelling in /proteins/compare.py
2. Enable saveEnsemble() to also save the atoms of ensemble in /ensemble/functions.py
3. fix a bug that parsePDB() always compresses PDB files to working directory if a local PDB folder is designated.
4. Add two more arguments to eigh() used in calcModes() to allow specifying number of modes (original code used in calcModes).
> Several Changes

- prody/__init__.py
It seems that the logger does not honor verbosity settings in the config. I think this change fixes that.
> Logger verbosity

- prody/trajectory/psffile.py
In python 3, strings represented by bytes need to be explicitly defined.
> Fix Python3 parsePSF error

- prody/atomic/select.py
- prody/dynamics/plotting.py
Fix following warning:
C:\GitHub\ProDy\prody\atomic\select.py:1326: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
if tokens[0] == 'and' or tokens[-1] == 'and':
> Fix a future warning

- prody/__init__.py
- prody/dynamics/analysis.py
http has been changed to https in checkUpdates(); 
Some of words corrections in analysis.py suggested by Ivet previously.
http://prody.csb.pitt.edu/manual/reference/dynamics/analysis.html cannot be re-generated anymore. analysis.rst has been renamed as calcTransformation. I don't know why. And there is no extension "rst" in the new file name.
docs/reference/dynamics/analysis.rst → docs/reference/dynamics/calcTransformation https://github.com/prody/ProDy/commit/3ca86ad6be3bc2d6e37218e119719b953ec39240
> http -> https in checkUpdates(); words corrections in analysis.py

- prody/proteins/functions.py
If py3Dmol has been imported (e.g., within a Jupyter notebook, which is the only place it makes sense), then showProtein will render using py3Dmol instead of matplotlib.
For example, see:
http://mscbio2025.csb.pitt.edu/notes/prody1.slides.html#/43
> Integration with py3Dmol

- prody/proteins/pdbfile.py
NumPy will throw an error in the future if passed a non-integer number in the future. Use the truncating integer division operator to guard against this.
> Use truncating integer division

- prody/measure/measure.py
- prody/sequence/msatools.c
To compile on Visual Studio 2015, (void *) must be cast to (char *) to make the pointer size explicit. See https://msdn.microsoft.com/en-us/library/1kay26wa.aspx?f=255&MSPPError=-2147217396
> vs 2015 compilation fix: set size of pointer

- prody/dynamics/saxsConstants.h
- prody/dynamics/saxstools.c
Fix following compiling errors on Windows (VS C compiler has a [more strict rule](https://msdn.microsoft.com/en-us/library/eff825eh.aspx?f=255&MSPPError=-2147217396)):
prody\dynamics\saxstools.c(865): error C2057: expected constant expression
prody\dynamics\saxstools.c(865): error C2466: cannot allocate an array of constant size 0
prody\dynamics\saxstools.c(865): error C2133: 'atom': unknown size
prody\dynamics\saxstools.c(867): error C2057: expected constant expression
prody\dynamics\saxstools.c(867): error C2466: cannot allocate an array of constant size 0
prody\dynamics\saxstools.c(867): error C2133: 'mol_type': unknown size
prody\dynamics\saxstools.c(1120): error C2057: expected constant expression
prody\dynamics\saxstools.c(1120): error C2466: cannot allocate an array of constant …
> Fix compiling errors on Windows

- prody/proteins/pdbfile.py
tested on:
```
Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109] on linux
```
> fix: int casting error in proteins/pdbfile  #369

- prody/dynamics/analysis.py
- prody/dynamics/plotting.py
Doing 3N to N square sum in two separate loops rather than nested loops
gives a massive speed up (we're going from N**2 to 2*N)
Also fixed some things in the default file naming for writePerturbResponse
and made it work for missing residues and residues being in only some chains.
> Improved calcPerturbResponse and writePerturbResponse

- prody/atomic/atomic.py
- prody/ensemble/__init__.py
- prody/ensemble/functions.py
- add a function `buildPDBEnsemble` that can be used to create `PDBEnsemble` from a list of PDBs conveniently, e.g.:
`ensemble = buildPDBEnsemble(referencePDB, PDBs, title=title, labels=labels)`
- now all atomic classes have `getTitle()` (non-`AtomGroup` classes will return the title of their `AtomGroup`).
> Implemented buildPDBEnsemble

- prody/ensemble/functions.py
Relaxed the constraint of argument `PDBs` in `buildPDBEnsemble`.
> a small change to `buildPDBEnsemble`

- prody/dynamics/analysis.py
- prody/dynamics/plotting.py
- prody/proteins/pdbfile.py
These changes shouldn't really do anything except add ease of use through having more options. Basically 3 changes (the first two are unnecessary except for showing forces have no effect):
1. Forces are now fully random rather than in the positive quadrant
2. If the user wants to check what happens from doing different things with the matrices from individual forces, this is now handled with dictionaries. The the user can choose whether to have a dictionary returned or stick with arrays, which can be read out into individual variables. (There is a commit associated with this because I missed a square bracket implementing it.)
3. showPerturbResponse now has the effectiveness and sensitivity clipped at the last residue to align with the PRS matrix
> Updated calcPerturbResponse and showPerturbResponse

- prody/proteins/localpdb.py
- prody/proteins/wwpdb.py
- Partly fixed the obsolete PDB ID problem (#380). Now fetchPDB will try to use HTTP (it can find obsolete PDBs) if FTP couldn't locate the ID. Soon I will implement a function that can redirect the obsolete PDB IDs to the new IDs according to the official obsolete list (ftp://ftp.wwpdb.org/pub/pdb/data/status/obsolete.dat).
> Fixed failed downloading of obsolete PDBs

- prody/dynamics/analysis.py
- prody/dynamics/modeset.py
- prody/ensemble/functions.py
- Now calcPerturbResponse accepts Mode and ModeSet as input
- Fixed a bug where ModeSet.getCovariance weighs each mode with eigenvalue (the weight should be variance which is equivalent to 1/eigenvalue).
> Bug fixes in ModeSet.getCovariance

- prody/atomic/fields.py
- prody/chromatin/hic.py
- prody/proteins/header.py
- prody/proteins/pdbfile.py
- Added three secondary structure related attributes to AtomGroup: secid (helix or sheet id), secindex (helix or strand index), and secclass (helix class or strand sense).
- Accommodated assignSecstr and writePDB so that complete information on secondary structures can be read or written. *Note that the registrations of the beta sheets are not included in reading or writing, since for that a residue needs to store a reference to other residues, but I am not sure which attributes/data types I should use.
- Fixed a problem in HiC module where the bin size cannot be correctly recognized in some cases.
> writePDB now can write secondary structures to PDB files

- prody/dynamics/pca.py
- prody/ensemble/functions.py
- prody/proteins/functions.py
- Fixed a bug which causes n_modes in PCA.calcModes not functional.
- trimPDBEnsemble now takes 'selstr' as input so it will trimed the residues NOT selected by 'selstr'.
- Fixed a bug where showProtein uses up all the colors if the number of molecules is very large.
> Several fixes

- prody/sequence/msa.py
This was necessary because the label had white space at the end.
> Added substring matching for msa.getIndex

- prody/proteins/ciffile.py
auth_seq_id should be field number 16 and
pdbx_PDB_model_num should be field number 20.
The current parser breaks on parsingCif files.
> ciffile field numbers

- prody/proteins/ciffile.py
The parser is crashing for proteins (ex: 4v6w) for which the atom field does not have two spaces after "ATOM":
"ATOM 1      N N     . PHE A  1  4    ? -15.152  72.946   -53.601  1.00 70.00 ? 4    PHE Az N     1 "
> ciffile change line checking for ATOM/HETATM

- prody/dynamics/anm.py
- prody/proteins/emdfile.py
For ANM, I made it so that you can ask for all modes directly rather than the counter-intuitive asking for all modes by asking for None.
For parseEMD, I made it so it doesn't automatically make nodes but instead actually just parses an EMD/MRC2014 map and allows the user to make nodes later if that's what they want to do.
> Bug fix so n_modes='all' now works and changed some parameter defaults on parseEMD

- prody/dynamics/analysis.py
- prody/dynamics/compare.py
- prody/dynamics/plotting.py
- prody/ensemble/ensemble.py
- prody/ensemble/functions.py
- prody/ensemble/pdbensemble.py
- prody/measure/transform.py
- **added calcEnsembleENMs.**
- **added calcSignatureProfile and showSignatureProfile.**
- renamed calcCovOverlap to calcSpectralOverlap and also kept the old name.
- **redesigned calcOverlapTree.** The function is separated into two parts, first, calcSpectralDistances is used to obtain the distance matrix, and then calcTree, which is an original function of prody, is used to obtain the tree.
- added an argument 'method' to calcTree, so that the tree can be built by either Neighour Joining or UPGMA.
- now Ensemble.getRMSDs has an option to obtain them pairwisely.
- a small bug fixed in getRMSDs where it could result zero output.
> Changes related to SignDy

- prody/dynamics/analysis.py
- prody/dynamics/functions.py
- prody/ensemble/ensemble.py
- prody/ensemble/functions.py
- prody/ensemble/pdbensemble.py
- a major change to trimPDBEnsemble. Now the function support "soft trimming" by setting hard to False. "Soft trimming" uses selection to trim the ensemble so that the original atomgroups can be saved and later used by reduceModel or sliceModel. Another advantage of this is that user can undo the trimming by:
```
ag = ensemble.getAtoms().getAtomGroup()
ensemble.setAtoms(ag)
```
- several changes to Ensemble and PDBEnsemble to support "soft trimming".
> Large changes to ensemble module

- prody/__init__.py
- prody/dynamics/plotting.py
- prody/dynamics/signature.py
- prody/utilities/catchall.py
- Removed new_fig from plotting functions. Now they are either universally controlled by `confProDy('auto_show')`, or they can be controlled by the argument called 'figure'. If figure is set to None, then a new figure will be created. If not, no matter what 'auto_show' value is, plots will be drawn on the figure.
- We will only need to deal with this figure creation problem in base functions like showAtomicData or showMatrix, hopefully, other plotting functions will build on them and no longer need to deal with it. Stay tuned for further updates but **showSignatureProfile is now working**.
> Removed new_fig from plotting functions

- prody/dynamics/compare.py
- prody/proteins/pdbfile.py
Now parsePDB accepts multiple PDB identifiers as input. The PDB identifier can contain chain identifier at the end. For example:
prot = parsePDB('1p38:A')
prots = parsePDB('1p38', '3tt1', chain='A')
prots = parsePDB('1p38', '3tt1', chain=['A', 'B'])
prots = parsePDB('1p38A', '3tt1B')
prots = parsePDB('1p38:A', '3tt1:B')
> parsePDB accepts multiple PDB identifiers as input

- prody/ensemble/functions.py
- prody/proteins/compare.py
- Added a mapping function: mapOntoChainByAlignment
- In buildPDBEnsemble, when mapping the chains to the reference, an additional iteration number `index` will be given to `mapping_func`.
Ideally, the alignment should work like this:
```
alignments = [...] # define your alignment duplets
ens = buildPDBEnsemble(ref, PDBs, alignments=alignments, mapping_func=mapOntoChainByAlignment)
```
This should work but I don't have alignments to test on, so please let me know if it doesn't work.
> change to buildPDBEnsemble to take predefined alignments as input

- prody/ensemble/functions.py
- prody/proteins/compare.py
- prody/sequence/analysis.py
- prody/sequence/msa.py
- prody/utilities/pathtools.py
- Allowed mapOntoChainByAlignment to take MSA input ("msa" is then removed).
- Fixed a bug in mapOntoChain when building based on predefined alignments.
- Fixed Windows related issues when running external programs, such as ClustalW2.
- Changed "prefix" to "title", and moved "title" and "labels" to optional arguments from kwargs because of their importance.
- Now buildMSA and alignSequencesByChain do not take PDB identifiers as input because of the dependency issues of parsePDB. Besides, parsePDB can take multiple inputs now so for users it is just one line of code.
> Changes related to building dimers

- prody/dynamics/signature.py
- prody/ensemble/functions.py
- prody/proteins/compare.py
- prody/utilities/catchall.py
- now `mapOntoChain` will be forced to use pairwise alignment if `pwalign` is set to `True`. The default behavior is used by setting `pwalign` to `None`.
- `fast` option is removed from `mapOntoChain` as it will be handled by the logger's verbosity.
- showVarianceBar now shows no highlights by default.
> Small changes

- prody/atomic/atomic.py
- prody/dynamics/signature.py
- prody/ensemble/ensemble.py
- prody/ensemble/pdbensemble.py
- prody/tests/ensemble/test_ensemble.py
- Ensemble selection should be more robust. There could be further improvements making ensemble selection easier to understand and operate.
- Now Ensemble.addCoordset can add coordsets having the length of selected atoms. The rest will be assumed to be the reference coordinate.
- `Atomic` classes now have an extra function called `toAtomGroup` which functions exactly the same as `copy`.
> Improved ensemble selection

- prody/ensemble/ensemble.py
- prody/ensemble/pdbensemble.py
- prody/sequence/analysis.py
- prody/sequence/msa.py
- prody/sequence/sequence.py
- prody/tests/ensemble/__init__.py
- prody/tests/ensemble/test_ensemble.py
- prody/tests/ensemble/test_pdbensemble.py
- prody/utilities/misctools.py
- Improvement of `addCoordset`. If `degeneracy=True` and `coords` is `Atomic`, then `getCoords` instead of `getCoordsets` will be used to retrieve coordinates. **This will allow using `setACSIndex` to alter active coordinates when adding an atom with multiple coordinate sets.**
- `other._atoms` will be used as the new atoms when adding ensembles if `self._atoms` isn't available. The same goes with weights.
- Bug fixes to `showAlignment` and **now it assumes default labels if labels are not available**. 
- Changed the default title for `MSA.__add__` in order to be consistent with other classes, such as `Ensemble`.
> Added tests for PDBEnsemble associated MSA

- prody/dynamics/editing.py
- prody/dynamics/signature.py
- prody/ensemble/ensemble.py
- Added ANM support to signature functions (not finished).
- **Now matching is performed right after ENM ensemble is calculated**. This will partly solve the 'bulb' issue when only a slice of the ensemble is given to the function. This feature can be disabled by passing `match=False` to `calcEnsembleENMs`.
- Other slight changes.
> Adding ANM support to signature functions

- prody/dynamics/signature.py
- Removed Signature to sdarray which is now a subclass of numpy.ndarray.
- Added documentation to `ModeEnsemble` (to be continued).
Notes on `sdarray`:
`sdarray` functions exactly the same as :`numpy.ndarray`, except that `sdarray.mean`, `sdarray.std`, `sdarray.max`, `sdarray.min()` are overriden. Average, standard deviation, minimum, maximum, etc. are weighted and calculated over the first axis by default.
Suppose:
```
In [1]: from prody import sdarray
In [2]: from numpy import mean
In [3]: sdarr = sdarray([[1, 2, 3], [4, 5, 6]], weights=[[0, 1, 1], [1, 1, 1]])
Out[3]:
sdarray([[1, 2, 3],
[4, 5, 6]])
weights=
array([[0, 1, 1],
[1, 1, 1]])
```
Then if we use the `sdarray.mean`: 
```
In [4]: sdarr.mean()
Out[4]: array([4., 3.5, 4.5])
```
it will compute the **weighted** average over the …
> Implementation of sdarray

- prody/dynamics/pca.py
- prody/dynamics/perturb.py
- prody/dynamics/signature.py
- prody/ensemble/ensemble.py
- prody/ensemble/functions.py
- prody/measure/measure.py
- prody/proteins/pdbclusters.py
- prody/proteins/pdbfile.py
- prody/trajectory/dcdfile.py
- prody/utilities/logger.py
- Added a verbosity level called 'progress' that is above 'info' and below 'warn'.
- Now when a `LOGGER.progress` is initiated, the verbosity is automatically set to 'progress'. The original verbosity will be restored by `LOGGER.update` the step to the total steps, or by call `LOGGER.finish`. **It is recommended to call `LOGGER.finish()` after the progress is done.**
- Fixed the flashing problem when progressing.
> Improvement of LOGGER.progress

- prody/sequence/analysis.py
This is to prevent ClustalW2 saying that two labels are the same because the first parts are.
> bug fix to buildMSA because ClustalW2 can't handle labels with spaces

- prody/ensemble/functions.py
`refpdb` is renamed to `ref` and moved to the second position. So we should use it like this:
```
ens = buildPDBEnsemble(PDBs, refpdb)
```
`ref` is optional, and if it is omitted then the first structure in PDBs will be assumed to be the reference.
`buildPDBEnsemble` is relatively new function so I doubt if anyone is using it except for us. So this change of behavior, although it affects coding, should be acceptable and should be made early.
> Changed the argument order in buildPDBEnsemble

- prody/database/pfam.py
I realised these are actually uniprot numbers and in most cases the discrepancy can be extracted from the pdb header.
> Improvements to parsePfamPDBs to use residue numbers

- prody/atomic/__init__.py
- prody/atomic/atommap.py
- prody/atomic/chain.py
- prody/atomic/functions.py
- prody/atomic/hierview.py
- prody/dynamics/editing.py
- prody/dynamics/plotting.py
- prody/measure/measure.py
- prody/utilities/catchall.py
- prody/utilities/legacy.py
- prody/utilities/misctools.py
- [extendModel] fixed the bug of duplicated atoms generated in, for example, a backbone model (see #636).
- [sliceAtomicData, extendAtomicData] Generalized these two functions for any axis (or axes), which should be more consistent with `numpy`.
- [HiewView] Added `getHiewView` to `AtomMap`.
> Bug fix to extendModel and other changes

- prody/proteins/compare.py
so that if a `subset` is set then the atoms (which is the mobile structure) will be also selected based on that.
> a small fix to mapOntoChain

- prody/dynamics/plotting.py
- [showAtomicMatrix] now `atoms` argument can be a list of `Atomic` objects. For example,
```
from matplotlib.pyplot import *
ion()
pathPDBFolder('.')
prot = parsePDB('3tt1', subset='ca', chain='AB')
gnm = GNM()
gnm.buildKirchhoff(prot)
gnm.calcModes()
cc = calcCrossCorr(gnm)
figure()
showAtomicMatrix(cc, atoms=prot)
part = prot.select('resnum < 50')
subcc = sliceAtomicData(cc, prot, part, axis=0)
figure()
showAtomicMatrix(subcc, atoms=[part, prot])
```
- [sliceAtomicData] changed the default value for `axis` to `None`. This should be more consistent with `numpy`.
> Improved showAtomicMatrix and other changes

- prody/dynamics/plotting.py
- prody/ensemble/functions.py
- prody/utilities/catchall.py
- prody/utilities/misctools.py
- Added `gap` and `overlay` to `showAtomicLine`. Example code:
```
from pylab import *
ion()
prot = parsePDB('3tt1', subset='ca', chain='AB')
prot.setData('domain', prot.getChids())
part = prot.select('resnum < 50 or resnum > 100')
gnm = GNM()
gnm.buildKirchhoff(prot)
gnm.calcModes()
sqf = calcSqFlucts(gnm[:3])
subsqf = sliceAtomicData(sqf, prot, part)
dy = ones(len(subsqf)) * 0.01
x = part.getResnums()
figure()
subplot(3, 2, 1)
showAtomicLines(subsqf, atoms=part, gap=True)
subplot(3, 2, 2)
showAtomicLines(subsqf, atoms=part, dy=dy, gap=True)
subplot(3, 2, 3)
showAtomicLines(subsqf, atoms=part, gap=False)
subplot(3, 2, 4)
showAtomicLines(subsqf, atoms=part, dy=dy, gap=False)
subplot(3, 2, 5)
showAtomicLines(subsqf, atoms=part, overlay=True)
legend()
subplot(3, 2, 6) …
```
> Improved showAtomicLine

- prody/database/pfam.py
This fixes issue #362, which is due to the PDB file containing an incorrect Uniprot ID. The fix is to try the Uniprot accession instead and if that fails then to use parsePDB and repeat with the sequence from the Atomgroup.
>  made searchPfam try with accession then sequence if it gets a bad Uniprot ID.

- prody/__init__.py
- prody/proteins/header.py
- prody/tests/proteins/test_pdbfile.py
- Suppressed an error when no header is present in the pdb file. This will make `auto_secondary` work better on pdb files with no header.
- Turned `auto_show` to off by default.
> Two changes

- prody/ensemble/functions.py
- prody/proteins/pdbfile.py
I was surprised to find that subset='calpha' was applied so I added it to the documentation so other users won't be.
> bug fix for parsePQR

- prody/dynamics/compare.py
- prody/dynamics/functions.py
- prody/dynamics/signature.py
- `turbo` option in `calcEnsembleSpectralOverlaps` eliminates redundant computations during iterations. For single calculation, `turbo` will compromise the speed.
- `turbo` option in `matchModes` computes match of modes in parallel (each mode set is independently matched to the reference).
- Both options allow speed-up about 40%.
- Documentation changes.
> Added turbo options to calcEnsembleSpectralOverlaps and matchModes

- prody/proteins/functions.py
Previous changes disabled the ability to view ensembles of molecules.  Also, two viewers were being created.  This restores the previous behavior, although you may want to consider adding a kwarg option for loading multiple coordinate sets into frames (addModelsAsFrames instead of addaddAsOneMolecule).
Example of code that was broken and is fixed with this patch:
```
import prody
import py3Dmol
ubi = prody.parsePDB('2lz3')
prody.showProtein(ubi)
```
> fixes to py3Dmol support

- prody/ensemble/ensemble.py
- prody/ensemble/pdbensemble.py
This fixes a few errors in PDBEnsemble initialization (fixes in brackets):
1. Ensemble `_getCoords` method had no argument `selected` (added `selected` and made the behaviour match `getCoords`)
2. PDBEnsemble `_msa` attribute does not exist at the PDBEnsemble `addCoordset` step (reordered `__init__` steps so `_msa` is initialized first)
3. `setCoordset `step complains "coordinates of None are not set" (changed `setCoords(title.getCoords())` to `setCoords(title)`)
I also fixed a perceived bug but now I have a potentially bad/unexpected behaviour:
- initializing from an Atomgroup gives a PDBEnsemble with an MSA but when initializing from an Ensemble it has None so I added a block setting `_atoms` before `addCoordsets` but it means that we always have `_atoms` set even though the user didn't …
>  bug fix for initializing PDBEnsembles from Atomgroups and Ensembles 

- prody/dynamics/analysis.py
- prody/dynamics/compare.py
- prody/utilities/catchall.py
call `calcSpectralOverlap(..., weighted=True)` to use the mode weights instead of variances in the covariance overlap calculations
> Changes to calcSpectralOverlap

- prody/database/pfam.py
This sometimes causes an exception "The read operation timed out"
> missing timeout option in openURL() in fetchPfamMSA()

- prody/measure/measure.py
Corrections to avoid:
1) ValueError (operands could not be broadcast together with shapes ...) when calling calcGyradius(p, weights=p.getMasses())
2) Uncorrect calculation of the (mass weighted) radius of gyration
> Mass weighted calcGyradius bugs

- MANIFEST.in
- pyproject.toml
Hello!
When trying to install ProDy into a clean environment using pip and `requirements.txt`, sometimes pip tries to install ProDy before NumPy, and it causes `No files/directories in /tmp/pip-build-xxxxxxx/prody/pip-egg-info (from PKG-INFO)` error (which is not very helpful).
Here's a `Dockerfile` to reproduce (same on 18.04):
```Dockerfile
FROM ubuntu:16.04
RUN apt-get update && apt-get -y install python3 virtualenv build-essential && apt-get clean
RUN virtualenv -p python3 venv
RUN printf "numpy>=1.10\nscipy>=0.16\nprody>=1.8.2" > /requirements.txt
RUN bash -c 'source venv/bin/activate && pip install -r /requirements.txt'
CMD ["/bin/bash"]
```
Doing `pip install` in two-step (first, install NumPy and SciPy, and only afterward install ProDy) works, but is rather inconvenient.
ProDy is …
> Add pyproject.toml to resolve build dependency on NumPy

- prody/proteins/compare.py
It still has the right formatting for buildPDBEnsemble if the reference is a single chain but otherwise it returns mappings for all the chains.
> bug fix so mapChainByChain returns multiple chains if desired

- prody/proteins/pdbfile.py
Without this change, I get the following error:
/home/jkrieger/Documents/code/ProDy/prody/proteins/pdbfile.pyc in parsePDB(*pdb, **kwargs)
127             LOGGER.update(i, 'Retrieving {0}...'.format(p+c), 
128                           label='_prody_parsePDB')
--> 129             result = _parsePDB(p, **kwargs)
130             if not isinstance(result, tuple):
131                 if isinstance(result, dict):
/home/jkrieger/Documents/code/ProDy/prody/proteins/pdbfile.pyc in _parsePDB(pdb, **kwargs)
199     if chain != '':
200         kwargs['chain'] = chain
--> 201     result = parsePDBStream(pdb, **kwargs)
202     pdb.close()
203     return result
/home/jkrieger/Documents/code/ProDy/prody/proteins/pdbfile.pyc in parsePDBStream(stream, **kwargs)
274             hd, split = …
> bug fix to _parsePDBLines for large PDB files

- prody/proteins/pdbfile.py
This could be useful for comparing PDB files containing selections back to full PDB files. Some programs use that too e.g. PLUMED for RMSD calculations: "Note that RMSD should be provided a reference structure in pdb format and can contain part of the system but the second column (the index) must reflect that of the full pdb so that PLUMED knows specifically which atom to drag where." (taken from https://plumed.github.io/doc-v2.5/user-doc/html/belfast-5.html#belfast-5-target)
> Option to not renumber serials for writing PDB files

- prody/dynamics/rtb.py
- prody/dynamics/rtbtools.c
C `long` on Windows 64-bit is a 32-bit integer type. So added data type conversion to int32 numpy array in the RTB module to make sure the consistency across platforms. 
In addition, added code to explicitly ensure the `coords` array is in 'C' order.
> Compatibility fix for RTBtools on Windows

- prody/utilities/catchall.py
reorderMatrix needs names that can be found on the tree in the order that corresponds to the input matrix. If none are provided then it generates a list of indices converted to strings ('1', '2', '3', ...), which in most cases doesn't help. We therefore get an error when we don't provide names when the step that searches for the names in the tree fails. I instead made it so that we get an error if no names are provided as well as type checks, which were missing.
> added missing checks to reorderMatrix

- prody/trajectory/trajectory.py
This now fixes #862. The problem is that Python 3 handles slices differently and gets np.int64 from them not standard int.
> bug fix for indexing trajectories in python 3

- prody/proteins/functions.py
- prody/utilities/misctools.py
Otherwise, we get the following:
```
In [8]: showProtein(kg2, mode=anm[0])
<ipython-input-8-30ce98251e8d> in <module>()
----> 1 showProtein(kg2, mode=anm[0])
/data/jkrieger/programs/ProDy/prody/proteins/functions.pyc in showProtein(*atoms, **kwargs)
333                             xyz2 = XYZ2[i]
334                             mutation_scale = kwargs.pop('mutation_scale', 10)
--> 335                             drawArrow3D(xyz, xyz2, mutation_scale=mutation_scale, **kwargs)
336 
337             water = atoms.select('water and noh')
/data/jkrieger/programs/ProDy/prody/utilities/drawtools.pyc in drawArrow3D(*xyz, **kwargs)
46 …
```
> bug fix to showProtein with mode and scale

- prody/dynamics/exanm.py
We now have a user-friendly error rather than one from python that doesn't make much sense.
> bug fix for exanm buildMembrane when input is not from opm/ppm

- setup.py
I just came across this commit in my old master. I don't know if it's helpful or not. We still need to find a way of checking what compilers are on the system and not just depend on system type.
> make sure on MacOSX C extensions are compiled using clang compilers

- prody/proteins/header.py
This information can useful for linking PDB models from cryo-EM to the original EMDB maps.
This was part of devel-2 but it shouldn't have been.
> added related_entries to PDB header

- prody/dynamics/compare.py
- prody/dynamics/nma.py
so we can get indices without starting with modesets
Before, it would fail because ANM objects don't have getIndices. Now it can cope with that.
> bug fix to matchModes 

- prody/proteins/compare.py
This change should allow the following settings:
```
ref: ABCDE
atm: AB-CD
```
```
ref: ABC-E
atm: ABCDE
```
> Small changes to mapChainByChain to allow more flexible correspondence settings

- prody/dynamics/signature.py
The line I deleted is redundant because subfamilies are already defined above and problematic because of the python3 dict_keys type object not splitting into entries in the array.
> bug fix to calcSubfamilySpectralOverlaps

- prody/utilities/misctools.py
getMasses() is modified to return the atomic mass of any element using the 'atom_weights' dictionary from Bio.Data.IUPACData
( currently approximate masses are returned for most comment elements only: C, N, S, O, H )
> Get masses from IUPACData

- prody/proteins/compare.py
The previous code passes the assignment of chid so that the previous value of chid is used in the next code block. The fix is that we continue on to the next round of the loop and don't run that code at all if no match is found.
> bug fix to mapChainByChain handling flexible cases

- prody/proteins/emdfile.py
If no kwargs are provided to parseEMD then the default values for _parseEMDLines mean that we return the raw EMD map but if the user sets n_nodes > 0 then it make nodes with TRN and does not return the EMD map unless the user specifically ask for it.
> set default behaviour of _parseEMDLines based on n_nodes

- prody/ensemble/ensemble.py
- prody/ensemble/functions.py
- prody/ensemble/pdbensemble.py
- prody/measure/transform.py
- prody/proteins/compare.py
- prody/proteins/functions.py
- prody/utilities/catchall.py
- prody/utilities/legacy.py
- prody/utilities/misctools.py
Major changes:
- Implemented `mapChainOntoChain` that maps a `Chain` instance onto another and let `mapOntoChains` use `mapChainOntoChain` when in its loop over chains.
- Implemented `mapOntoChains` that calculates mappings of chains between two structures in a pairwise fashion.
- Implemented `combineAtomMaps` for "optimally" combining atommaps obtained from `mapOntoChains` or `mapOntoChain`.
- Implemented `alignChains` for aligning two structures with `mapOntoChains` and `combineAtomMaps`.
- Rework of `buildPDBEnsemble`. 
Now instead of `mapping_func`, a `match_func` should be passed to the function. The `match_func` takes **exactly two** parameters `chain1` and `chain2` and determines if these two chains should be tried to be mapped. Built-in options for `match_func` includes: 
- …
> Rework of the structure mapping functions

- prody/__init__.py
- prody/atomic/atomgroup.py
- prody/ensemble/functions.py
- prody/proteins/pdbfile.py
Working towards solving #798.
- Now `parsePDB(..., bonds=True)` can evaluate `CONECT` entries in the PDB files. These entries are interpreted as the `Bond` objects in ProDy.
- Added a setting called `auto_binds`, which when set to `True`, `parsePDB` will read `CONECT` entries by default.
> Enabled parsePDB to evaluate CONECT entries

- prody/dynamics/mode.py
The user can be confused if it just returns nothing.
> added warning instead of empty return for getHinges for 3D mode

- prody/dynamics/plotting.py
- prody/proteins/functions.py
I think the arrows are ugly so I'm providing an option to omit them.
The doc string used the old names for parameters, which still could be documented better.
> Improve documentation, add arrows option

- prody/proteins/header.py
The buildBiomolecules() function may apply the transforms specified in the PDB header to wrong chains if a biomolecule is defined by more than one transform (example: pdbID 4I8O biomolecule 3). This bugfix is supposed to solve the problem.
Explanation:
For each biomolecule, the function iterates through an array of transforms that define the biomolecule. But while each transform has its own set of chains that it should be applied to, current implementation applies all transforms to the set of chains specified for the first transform.
This PR changes the function behaviour so that each transform is applied to its own set of chains.
> Fix a bug in buildBiomolecules()

- prody/utilities/catchall.py
- prody/utilities/drawtools.py
- prody/utilities/misctools.py
The following is an RMSD tree shown in two orientations.
The following code reproduces the figures (given input data):
```
from matplotlib.pyplot import *
ion()
ens = loadEnsemble('seqid_reordered_proteases.ens.npz')
ens = ens[:20]
new_labels = ens.getLabels()
rmsds = ens.getRMSDs(pairwise=True)
tree = calcTree(new_labels, rmsds, method='upgma')
reordered_rmsds, rmsd_reordering_indices = reorderMatrix(
rmsds, tree, new_labels)
figure()
show = showMatrix(reordered_rmsds, y_array=tree, x_array=tree, origin='lower')
figure()
show = showMatrix(reordered_rmsds, y_array=tree, x_array=tree, origin='upper')
```
> Made showMatrix show trees properly on both x- and y-axis

- prody/ensemble/ensemble.py
- prody/ensemble/pdbensemble.py
Without this change then the PDBEnsemble has an MSA of the wrong size, which matches the selected atoms not the full atoms, and that causes problems for getMSA and hence trimPDBEnsemble:
```
In [57]: lisa_pdbens                                                                                                                        
Out[57]: <PDBEnsemble: Ensemble combined_trajectory_receptor_calpha (0:13000:1) (13000 conformations; selected 451 of 455 atoms)>
In [58]: lisa_pdbens.getAtoms()                                                                                                             
Out[58]: <Selection: 'index 4 to 454' from starting_structure_calpha (451 atoms)>
In [59]: msa = lisa_pdbens.getMSA() …
```
> bug fix for creating PDBEnsemble from selected Ensemble

- prody/dynamics/plotting.py
We can now support RGBA or RGB assignments for colors like we're supposed to be able to and I managed to generate this figure:
The code for it is as follows:
```
labels = ('DruGUI sim 1', 'DruGUI sim 2', 'DruGUI sim 3',
'DruGUI sim 4', 'DruGUI sim 5', 'DruGUI sim 6',
'Apo sim 1', 'Apo sim 2', 
'PTH sim 1', 'PTH sim 2', 'PTH sim 3')
slices = (slice(0, 2000), slice(2000, 4000), slice(4000, 6000),
slice(6000, 8000), slice(8000, 10000), slice(10000, 12000),
slice(12000, 13000), slice(13000, 14000), 
slice(14000, 16000), slice(16000, 18000), slice(18000, 19000))
cols = plt.cm.rainbow(np.linspace(0, 1, len(labels)))
plt.figure()
for l, c, s in zip(labels, cols, slices):
showProjection(combined_traj[s], whole_pca[:2],
label=l, c=c, markersize=3)
xmin, xmax = plt.xlim()
plt.xlim(xmin, xmax+8) …
```
> 2nd bug fix to c kwarg in showProjection

- prody/proteins/compare.py
Otherwise, we get lines like `Mapped: 1063 residues match with 77%% sequence identity and 95%% overlap.`
> fixed %% for reporting Mapped entries

- prody/database/dali.py
Otherwise it reports a less clear error and the user doesn't know what to do.
> errors for dali record not having any data yet

- prody/proteins/pdbfile.py
This is so as to make it easier to handle biomols. The current situation is that we get a mixed list containing atomgroups and lists that needs to be dealt with by the user e.g. 
```
In [1]: from prody import *                                                                                                
In [2]: results = parsePDB(['3hsy','3o21'], subset='ca', biomol=True)                                                      
@> 2 PDBs were parsed in 0.13s.
In [3]: results                                                                                                            
Out[3]: 
[<AtomGroup: 3hsy_ca biomolecule 1 (730 atoms)>,
[<AtomGroup: 3o21_ca biomolecule 1 (739 atoms)>,
<AtomGroup: 3o21_ca biomolecule 2 (750 atoms)>]]
```
With the new option, we have the option to create a …
> added extend_biomol option to parsePDB

- prody/dynamics/signature.py
Otherwise, we get the following error:
```
In [14]: showSignatureMode(anm_ens[:,0])                                                                           
TypeError                                 Traceback (most recent call last)
/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
60     try:
---> 61         return bound(*args, **kwds)
62     except TypeError:
TypeError: 'float' object cannot be interpreted as an integer
During handling of the above exception, another exception occurred:
TypeError                                 Traceback (most recent call last)
<ipython-input-14-e59f87640106> in <module>
----> 1 showSignatureMode(anm_ens[:,0]) …
```
> bug fix on sdarray numAtoms being a float

- prody/trajectory/psffile.py
Otherwise we get
```
(base) Jamess-MBP-2:peptide_models jkrieger$ ipython
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from prody import * 
...: import numpy as np 
...: import matplotlib.pyplot as plt 
...: plt.ion()                                                                                                                 
In [2]: ag = parsePDB('3hsy')                                                                                                     
@> 3hsy downloaded (3hsy.pdb.gz)
@> 6508 atoms and 1 coordinate set(s) were parsed in …
```
> bug fix on writing PSF without parsing PSF file

- prody/dynamics/signature.py
The error otherwise is
```
In [64]: anm_ens.getModeSets(0)                                                                                    
<ipython-input-64-78d2e854bb26> in <module>
----> 1 anm_ens.getModeSets(0)
~/Documents/code/ProDy/prody/dynamics/signature.py in getModeSets(self, index)
229         if index is None:
230             return self._modesets
--> 231         return self[index]._modesets
232 
233     def getArray(self, mode_index=0):
AttributeError: 'ModeSet' object has no attribute '_modesets'
```
> bug fix for getModeSets with int index

- prody/dynamics/plotting.py
This module adjusts text so that it doesn't overlap and changes with zooming. The output becomes
> added adjust_text to showProjection and showCrossProjection

- prody/utilities/catchall.py
> added xtickrotation to showMatrix

- prody/dynamics/perturb.py
This is a better way to facilitate using an external matrix without complicating the code.
> updated calcPerturbResponse docs for ext matrix from PCA

- prody/dynamics/plotting.py
An update to matplotlib means cmap changed and it doesn't have an attribute `.color`. This is the fix to the problem. It wasn't necessary to change anything else.
> bug fixes to showProjection around colors

- prody/dynamics/signature.py
Otherwise the error is
```
showSignatureVariances(anm_ens_20[:,0], fract=False)                                                           
IndexError                                Traceback (most recent call last)
<ipython-input-25-c113ce977cda> in <module>
----> 1 showSignatureVariances(anm_ens_20[:,0], fract=False)
~/Documents/code/ProDy/prody/dynamics/signature.py in showSignatureVariances(mode_ensemble, **kwargs)
1562     labels = ['mode %d'%(i+1) for i in indices][::-1]
1563 
-> 1564     show = showSignatureDistribution(sig, label=labels, **kwargs)
1565 
1566     xlabel('Variance')
~/Documents/code/ProDy/prody/dynamics/signature.py in showSignatureDistribution(signature, **kwargs)
1507 …
```
> fix for showSignatureVariances (showSignatureDistribution) with 1 mode

- prody/ensemble/functions.py
That way, the user has the option to not superpose the ensemble at all and just analyse it as is.
> added superpose False option to buildPDBEnsemble

- prody/ensemble/ensemble.py
- prody/ensemble/functions.py
- prody/proteins/compare.py
Despite being checked, objects of `SimpleChain` are avoided to be mentioned in error or warning messages in order not to confuse users (`SimpleChain` is not designed to be exposed to users).
> Modified mapping functions to be compatible with SimpleChain input

- prody/ensemble/functions.py
Two problems are fixed here:
1. The current form accepts single structures and throws an error when it iterates through the atoms in them. Therefore, a list-like has to be checked for instead of just using `len`, which corresponds to `numAtoms` for atomgroups. Only then can we use `len` to check the length of the list-like.
2. The list is allowed to have one element if `degeneracy=False` because then you have multiple structures from one atomic so that gets included in the check too.
> error fix for buildPDBEnsemble with multi-state PDB

- prody/dynamics/editing.py
- prody/dynamics/functions.py
- prody/dynamics/perturb.py
- prody/dynamics/signature.py
- prody/ensemble/ensemble.py
- Added `trimModel` that simply slice the connectivity matrix (instead of modes as does by `sliceModel`).
- Added `calcSignaturePerturbResponse`.
- `calcENM` now accepts `numpy.ndarray` as input.
- Added `getIndices` and `setIndices` to `Ensemble` (and `PDBEnsemble`).
> Few changes to SignDy functions

- prody/dynamics/functions.py
- prody/dynamics/nma.py
- prody/dynamics/perturb.py
- prody/dynamics/plotting.py
- prody/dynamics/signature.py
- prody/ensemble/pdbensemble.py
- prody/proteins/compare.py
- prody/utilities/catchall.py
- prody/utilities/misctools.py
Basically now SignDy excludes dummy atoms from mode calculations (before they will be represented by ensemble-averaged coordinates). In this way, columns with zero occupancies will not give extra zero modes and unrealistic spikes in results (they were basically free particles since the average coordinate for them will be [0, 0, 0]).
> Improved how dummy nodes are treated in SignDy functions

- prody/proteins/pdbfile.py
Otherwise, it runs until the LOGGER complains:
```
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import os 
...: from prody import * 
...: import numpy as np 
...: import matplotlib.pyplot as plt 
...: import matplotlib 
...: plt.ion() 
...:  
...: proc = 3 
...:  
...: pdb = [f for f in os.listdir('.') 
...:        if f.endswith('redocking.pdb')] 
...: ag = parsePDB(pdb, model=1) 
...:  
...: fname = pdb[0] 
...: peptide = fname.split('_')[0]                                                                                   
AssertionError                            Traceback …
```
> added error for providing parsePDB an empty list

- prody/trajectory/dcdfile.py
The error was
```
<ipython-input-5-c8cf0c2e82e5> in <module>
----> 1 writeDCD('step5_protein_1_frame_per_ns', run1, start=27, step=10)
~/Documents/code/ProDy/prody/trajectory/dcdfile.py in writeDCD(filename, trajectory, start, stop, step, align)
577         diff = i - prev
578         if diff > 1:
--> 579             trajectory.skip(diff-1)
580         prev = i
581         if isTrajectory:
AttributeError: 'Ensemble' object has no attribute 'skip'
```
Ensemble doesn't need that functionality because there's a frame reindexing step in the isEnsemble block anyway.
> bug fix for writeDCD with Ensemble and frame selection

- prody/dynamics/gnm.py
Now the default of calcGNM matches the default of buildKirchhoff.
> bug fix for calcGNM not having the right cutoff

- prody/dynamics/signature.py
Otherwise
```
In [71]: plt.figure(); showSignatureOverlaps(mode_ens_new, diag=False);                                
TypeError                                 Traceback (most recent call last)
<ipython-input-71-c1ba3b154254> in <module>
----> 1 plt.figure(); showSignatureOverlaps(mode_ens_new, diag=False);
~/Documents/code/ProDy/prody/dynamics/signature.py in showSignatureOverlaps(mode_ensemble, **kwargs)
1472         else:
1473             meanV = overlap_triu.mean(axis=-1).mean(axis=-1)
-> 1474             show = showMatrix(meanV)
1475 
1476     return show
~/Documents/code/ProDy/prody/utilities/catchall.py in showMatrix(matrix, x_array, y_array, **kwargs)
591 
592     im = ax3.imshow(matrix, aspect=aspect, …
```
> bug fix on showSignatureOverlap

- CONTRIBUTING.md
- prody/apps/apptools.py
- prody/atomic/fields.py
- prody/atomic/functions.py
- prody/database/goa.py
- prody/dynamics/__init__.py
- prody/dynamics/analysis.py
- prody/dynamics/bbenm.py
- prody/dynamics/entropy.py
- prody/dynamics/functions.py
- prody/dynamics/imanm.py
- prody/dynamics/perturb.py
- prody/dynamics/plotting.py
- prody/dynamics/rtb.py
- prody/dynamics/signature.py
- prody/dynamics/vmdfile.py
- prody/ensemble/functions.py
- prody/measure/measure.py
- prody/proteins/__init__.py
- prody/proteins/blastUniProtKB.py
- prody/proteins/ciffile.py
- prody/proteins/emdfile.py
- prody/proteins/pdbfile.py
- prody/utilities/catchall.py
- prody/utilities/misctools.py
_solveEig is based on the PCA calcModes. We may want to use the GNM one instead but it was more complicated to move.
Example:
```
In [1]: from prody import *                                                                                        
In [2]: o1 = parsePDB('3o21_CD.pdb', subset='ca')                                                                  
@> 750 atoms and 1 coordinate set(s) were parsed in 0.01s.
In [3]: calcPrincAxes(o1)                                                                                          
Out[3]: 
array([[-0.59801737,  0.24073971,  0.76447343],
[ 0.18045356,  0.96977582, -0.16422963],
[ 0.78090444, -0.03973978,  0.62338512]])
```
> added calcInertiaTensor, calcPrincAxes and _solveEig

- prody/utilities/misctools.py
I know this is part of #1112 but we really need it beforehand.
> fixed __all__ in misctools to have solveEig without underscore

- prody/proteins/pdbclusters.py
This warning gets triggered so rarely that basically no one noticed it was wrong before.
> fix pdbclusters warning

- prody/ensemble/functions.py
saveEnsemble still works for now but we get these warnings:
```
c:\users\james\code\prody\prody\ensemble\functions.py:52: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
attr_dict['_atoms'] = np.array([atoms, None])
c:\users\james\code\prody\prody\ensemble\functions.py:61: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
attr_dict['_msa'] = np.array([msa, None]) …
```
> saveEnsemble fix for coming numpy deprecation

- .travis.yml
- prody/atomic/atomgroup.py
Before this, flags weren't getting taken into account when adding AtomGroup objects and we were building biomolecules where amino acid ligands were not HETATM components. Now, they are and this isn't a problem.
> adding hetatms fix

- prody/atomic/atomic.py
- prody/atomic/select.py
- prody/atomic/selection.py
SELECT and isSelectionMacro are defined in atomic __init__.py and prody __init__.py
ParseException wasn't necessary to import separately.
> cleaned up unneeded/unused definitions

- prody/dynamics/signature.py
Before that we could get things like the following:
`<ModeEnsemble: 66 modesets (1 modes, 376 atoms)>`
> fixed ModeEns repr for 1 mode without s

- prody/proteins/ciffile.py
Before this, it was incrementing the resindices and splitting the first residue of every chain/segment after the first atom because the termini were in the wrong place.
> fixed bug with resindices/termini from mmCIF files

- prody/proteins/starfile.py
Two fixes:
1. In order to read out 'data' and 'fields' from non-loop entries, we need to index the raw dictionary for them in __getitem__ before trying to match the keys to data loops.
2. The blank or # lines should end data loops in order to get the next data entry.
> starfile_fixes

- prody/dynamics/plotting.py
This way we can use diag=True for the diagonal of an overlap matrix between two sets of modes with einsteinsum or diag=False for overlaps between one mode and a set of modes.
> fixed showOverlap and showCumulOverlap for one mode

- prody/proteins/blastpdb.py
The filename variable wasn't initialised and was only assigned in some branches of the if block.
> fixed blastPDB

- prody/atomic/hierview.py
Previously, the only way to index and get a Chain was to use a segment name in addition to a chain ID (see #1175):
```
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)]
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.
In [2]: ag = parseMMCIF('4v88')
@> 413613 atoms and 1 coordinate set(s) were parsed in 8.14s.
In [3]: ag.getHierView().getChain('BU')
In [4]: ag['FB','BU']
Out[4]: <Chain: BU from Segment FB from 4v88 (100 residues, 796 atoms)>
In [5]: ag[None,'BU']
```
Now, we can just supply the chain ID and it gives the same result:
```
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit …
```
> fixed getChain to work without segname

- prody/utilities/catchall.py
1. Matplotlib 2 for Python 2 doesn't have DivergingNorm, TwoSlopeNorm, or any other normalization method with a vcenter parameter. Therefore I added in a check for PY3K.
2. TwoSlopeNorm wasn't being used as the call was still for DivergingNorm so I aliased it.
3. showMatrix shouldn't try to import these things unless vcenter is used, because otherwise we get import errors whenever showMatrix is called if we don't have the right Matplotlib.
> py3 fix for showMatrix norm

- prody/atomic/atomgroup.py
- prody/proteins/pdbfile.py
- prody/utilities/misctools.py
This is alternative fix to close #1192.
It is much cleaner than the previous ones because it has a function in utilities/misctools.py rather than repeated code and is also optional and only activated when the kwarg packmol is set to True. 
The result for the PDB file in #1192 is as follows:
```
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)]
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.
In [2]: ag = parsePDB('1IYT_multi.pdb')
@> 3180 atoms and 1 coordinate set(s) were parsed in 0.04s.
In [3]: list(ag.getHierView())
Out[3]: 
[<Chain: A from 1IYT_multi (42 residues, 1908 atoms)>,
<Chain: B from 1IYT_multi (42 residues, 1272 …
```
> added packmol chain renumbering

- prody/proteins/pdbfile.py
Hybrid36 format starts after 99999, which itself stays the same. The next number is A0000.
> hybrid36 doc fix

- prody/database/charmmgui.py
- prody/utilities/catchall.py
- prody/utilities/drawtools.py
The IndexFormatter is needed by too many functions to lose it and matplotlib has had deprecation warnings for it for a while.
> moved IndexFormatter into ProDy before matplotlib removes it

- prody/database/charmmgui.py
- prody/database/quartataweb.py
1. Previously the browser was initialized (selected, tested, etc.) by going to quartataweb, which may surprise charmm-gui users.
2. Solved the problem of the solvation step taking too long by visiting the job retriever and reloading if the page has an error saying to do so. The `wait_for_text` function needed changing for this as unlike the membrane case, the page that comes is the one that we are waiting for so the error is exposed otherwise.
> CHARMM-GUI fixes

- prody/proteins/starfile.py
The previous code depends on ordering of the keys, which is different in Python 2 and may be different across systems too.
> starfile fixes for PY2

- prody/proteins/starfile.py
Comparing string literals with identity operator "is" is not a good practice and may cause unexpected bugs. The string class is in a sweet spot between value-type and object-type variables, and in Python, it is treated in a mixed fashion. Using "!=" here is the intended comparison.
> Minor fixes in starfile

- pyproject.toml
Actually is needed for Python 2.7 install to work. This is the error without it:
```
jkrieger@prody:/var/www/html/prody/ProDy-website-workdir/ProDy$ pip install -U . --user
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
warnings.warn(warning, RequestsDependencyWarning)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A 
future version of pip will drop support for Python 2.7.
Processing /var/www/html/prody/ProDy-website-workdir/ProDy
Installing build dependencies ... error
ERROR: Complete output from command /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip …
```
> re-edited pyproject

- prody/ensemble/functions.py
- prody/ensemble/pdbensemble.py
`PDBEnsemble._selstrs` is removed for several reasons:
- It causes a bug in `saveEnsemble` when saving `Ensemble` objects. This is a `PDBEnsemble` only attribute but it was saved as if it were an attribute in the base class. 
- It was implemented incompletely. This attribute was not addressed at all in editing operators such as `__add__` and `__getitem__`. Future additions of new attributes should be made carefully as there are many aspects (e.g. loading, saving, and editing) of the class to be considered before making the decision to add an attribute.
- It is not very useful. Atomic subsets can be created without a selection string, namely AtomMap, which is the subset class used for creating the `PDBEnsemble`. Even if there is a selection string, the users cannot use it unless they have …
> Removed selstrs from PDBEnsemble

- prody/apps/prody_apps/prody_pca.py
- prody/ensemble/ensemble.py
Otherwise the NMWiz ProDy Interface throws errors during PCA:
1. The number of modes is more than we have.
2. The output of the LOGGER about superposition.
> pca app/nmwiz fix

- prody/dynamics/analysis.py
This allows the calculation of theoretical anisotropic displacement parameters (ANISOU lines in PDB files) from ANM or PCA covariance matrices. 
These are the entries in the ANISOU lines in PDB files (https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ANISOU).
They are also described in Bahar et al.  Annu. Rev. Biophys. 2010: 
```In high-resolution crystallographic structures, the diffraction data are sufficiently detailed to refine six anisotropic displacement parameters (ADPs), instead of a single isotropic parameter, per atom. The ADPs for the ith atom are simply the six distinctive elements of the ith diagonal superelement (a 3 × 3 symmetric matrix) of C(3N). Three of these, 〈(Δxi)2〉, 〈(Δyi)2〉, and 〈(Δzi)2〉, provide information on the sizes of motions along …
```
> added theoretical ADPs calculation

- prody/proteins/pdbfile.py
Can now do the following:
```
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.
In [2]: emds = parsePDB('2686', '2687')
@> Retrieving 2686... [  0%]@> WARNING 2686 download failed ('https://files.rcsb.org/download/2686.pdb.gz' could not be opened for reading, invalid URL or no internet connection).
@> Retrieving 2687... [ 50%] 7s@> WARNING 2687 download failed ('https://files.rcsb.org/download/2687.pdb.gz' could not be opened for reading, invalid URL or no internet connection).
@> 2 PDBs were parsed in 12.90s.
In [3]: emds
Out[3]: 
[<prody.proteins.emdfile.EMDMAP at 0x2260d9d2d90>, …
```
> parsePDB extension to EMD files

- prody/atomic/select.py
In some cases, using `within` or `exwithin` in a selection string to select from a selection caused an indexing problem e.g.
```
$ ipython
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.
In [2]: ag = parsePDB('4nre', compressed=False)
@> PDB file is found in working directory (4nre.pdb).
@> 11230 atoms and 1 coordinate set(s) were parsed in 0.11s.
@> Secondary structures were assigned to 451 residues.
In [3]: pdb = ag.select('protein')
In [4]: pdb.select('exwithin 5 of resid 353')
IndexError                                Traceback …
```
> selection.select within fix

- prody/sequence/analysis.py
Previously, we were missing the first residue. Now it works:
```
$ ipython
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.
In [2]: pdb = parsePDB('3l4aA')
@> PDB file is found in working directory (3l4a.pdb.gz).
@> 1120 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> Secondary structures were assigned to 94 residues.
In [3]: sel = pdb['A'].select('protein and name CA')
In [4]: msa = parseMSA('PF01395_full_refined.sth')
@> 2324 sequence(s) with 107 residues were parsed in 0.02s.
In [5]: sel = trimAtomsUsingMSA(sel, msa)
@> PDB file is found in working directory (3l4a.pdb.gz).
@> 1120 atoms and 1 …
```
> fixed trimAtomsUsingMSA

- .travis.yml
We don't need Python 3.6 and 3.7 any more. Python 3.5 kept to ensure back-compatibility.
> reduced checks

- prody/proteins/compare.py
This should allow people to continue with other alignment methods if ccealign C/C++ extension isn't installed.
> ccealign import try except

- prody/atomic/atom.py
- prody/atomic/atomic.py
- prody/proteins/emdfile.py
We now have converters from ProDy Atom, Atomic and EMDMAP classes to TEMPy Atom, BioPy_Structure and Map objects. This also included addition to EMDMAP of functions and attributes for filename, origin and apix.
This enables pipelines such as the following:
```
from TEMPy.protein.scoring_functions import ScoringFunctions
from TEMPy.protein.structure_blurrer import StructureBlurrer
ne_map = parseEMD('2680')
ne, ne_header = parsePDB('4uqj', header=True)
ne_map_tempy = ne_map.toTEMPyMap()
ne_BioPy_Structure = ne.toTEMPyStructure()
blurrer = StructureBlurrer()
ne_blurred = blurrer.gaussian_blur(ne_BioPy_Structure,
ne_header['resolution'], 
ne_map_tempy, 
filename=ne.getTitle()+'.mrc')
ne_blurred.write_to_MRC_file(ne_blurred.filename)
sc = ScoringFunctions()
ccc = …
```
> TEMPy converters

- prody/dynamics/adaptive.py
- prody/dynamics/exanm.py
- prody/dynamics/functions.py
This allows us to use exANM in Adaptive ANM.
Test code:
```
n, o = parsePDB('3kg2-opm.pdb', '5ide', subset='ca')
n_am = alignChains(n, o, seqid=70, rmsd_reject=50, match_func=sameChid)[0]
n_am_mem = n_am.select('resnum 512 to 629 790 to 900')
o_mem = alignChains(o, n_am_mem.copy(), seqid=70,
overlap=0, rmsd_reject=50, match_func=sameChid)[0]
o_mem_alg, T = superpose(o_mem, n_am_mem,
weights=n_am_mem.getFlags("mapped"))
aa = calcAdaptiveANM(n_am, o, 20, n_max_modes=20,
model='exanm', aligned=True)
```
Result snippet:
```
@> Initialized Adaptive ANM with RMSD 25.107
@>
Starting cycle 1 with (Chain D from 3kg2-opm_ca -> Chain D from 5ide_ca) + (Chain C from 3kg2-opm_ca -> Chain C from 5ide_ca) + (Chain B from 3kg2-opm_ca -> Chain B from 5ide_ca) + (Chain A from …
```
> Adaptive ANM extension for membrane proteins

- prody/dynamics/adaptive.py
- prody/ensemble/ensemble.py
These are fixes to the logic and they make small changes in the results. The most notable change is that only 1 mode is used in early cycles rather than 2. Using 2 in the first cycle was what caused me to look into this more carefully in the first place.
We still get 15 cycles (giving an ensemble with 32 conformers including the start and end points) for the GroEL single subunit case like the tutorial. The RMSDs are also very similar.
Original:
```
Starting cycle 15 with 1gruA_ca
@> Hessian was built in 0.26s.
@> 518 modes were calculated in 0.35s.
@> Using 518 modes with square cumulative overlap 0.078
@> Current RMSD is 1.253
@>
Continuing cycle 15 with structure (Chain A from 1gr5A_ca -> Chain A from 1gruA_ca)
@> Hessian was built in 0.24s.
@> 518 modes were calculated in 0.33s.
@> …
```
> AdaptiveANM fixes

- prody/dynamics/editing.py
Otherwise, I get the following error because calcENM doesn't make an exANM object.
```
60
61     anm, ca = calcENM(n_opm.ca, n_modes=10, model='exanm', select='ca')
---> 62     n_mem = anm.getCombined()
63
64     n_mem_alg = applyTransformation(T, n_mem.copy())
AttributeError: 'ANM' object has no attribute 'getCombined'
In [2]: anm
Out[2]: <ANM: 3kg2-opm reduced (10 modes; 3116 nodes)>
```
> calcENM exanm fix

- prody/ensemble/ensemble.py
Fix for setting ensemble weights as None. Otherwise, we get this error:
```
----> 4 ensemble.setWeights(weights)
5 ensemble.addCoordset(coordsA.copy())
~\code\ProDy\prody\ensemble\ensemble.py in setWeights(self, weights)
386             raise AttributeError('first set reference coordinates')
387         try:
--> 388             self._weights = checkWeights(weights, self._n_atoms, None)
389         except ValueError:
390             weights = checkWeights(weights, self.numSelected(), None)
~\code\ProDy\prody\utilities\checkers.py in checkWeights(weights, natoms, ncsets, dtype)
71         ndim, shape, wtype = weights.ndim, weights.shape, weights.dtype
72     except AttributeError:
---> 73         raise TypeError('weights must be a numpy.ndarray instance')
74
75     if ncsets:
TypeError: …
```
> ens_setWeights_bug_fix

- docs/release/v2.0_series.rst
Currently the text size is wrong for the bullets:
I think I fixed this by fixing the indentation.
> release notes fixes

- docs/release/v1.11_series.rst
Also a wrong text size - this time because the bullet wasn't separated from the point above
> 1.11 release note fix

- prody/atomic/atomic.py
- prody/proteins/emdfile.py
AtomMap has None for dummies when iterating.
Therefore, we get the following error:
```
<ipython-input-16-7a0390781457> in <module>
----> 1 c_BioPy_Structure = c_alg.toTEMPyStructure()
~\code\ProDy\prody\atomic\atomic.py in toTEMPyStructure(self)
274             raise ImportError('TEMPy is needed for this functionality')
275
--> 276         return BioPy_Structure(self.toTEMPyAtoms())
~\code\ProDy\prody\atomic\atomic.py in toTEMPyAtoms(self)
263
264         if hasattr(self, 'getResnums'):
--> 265             return [atom.toTEMPyAtom() for atom in self if atom is not None]
266         else:
267             return [self.toTEMPyAtom()] …
```
> bug fixes for converting AtomMap to TEMPy

- prody/proteins/localpdb.py
This function addresses the need expressed in #1323 
It provides a new function to fetch files from the PDB regardless of format. The test case is as follows:
```
from prody import fetchPDBs
pdbs = ["3h5v", "4u6f", "2680"]
fnames = []
for pdb in pdbs:
filename = fetchPDBs(pdb)
fnames.append(filename)
print(fnames)
@> 3h5v downloaded (C:\Users\james\...\3h5v.pdb.gz)
@> pdb4u6f.ent.gz download failed. 4u6f does not exist on ftp.wwpdb.org.
@> PDB download via FTP completed (0 downloaded, 1 failed).
@> Downloading PDB files via FTP failed, trying HTTP.
@> WARNING 4u6f download failed ('https://files.rcsb.org/download/4U6F.pdb.gz' could not …
```
> added fetchPDBs

- docs/release/v1.1_series.rst
This one shouldn't affect anything except the website as it is in old release notes.
> missed depracat* typo

- prody/database/uniprot.py
In Python 3 on Ubuntu 20.20 with Windows Subsystem for Linux 2, the previous code yields the following error, which the new code fixes.
```
In [2]: uniprot_rec = searchUniprot('O97071')
<ipython-input-2-4a7191ded3ba> in <module>
----> 1 uniprot_rec = searchUniprot('O97071') 
/mnt/c/Users/james/code/ProDy/prody/database/uniprot.py in searchUniprot(id)
191     """
192
--> 193     data = queryUniprot(id)
194
195     return UniprotRecord(data)
/mnt/c/Users/james/code/ProDy/prody/database/uniprot.py in queryUniprot(id, expand, regex) 
152     data = XML(data)
153
--> 154     data = dictElement(data.getchildren()[0], …
```
> uniprot PY3 fix

- prody/ensemble/pdbensemble.py
fixes #1351 
The problem was with handling the case where the ensemble starts off empty. It was setting self._n_atoms using n_nodes from the added coordset but leaving the n_atoms variable used below as 0.
> pdbens addcoordset fix

- prody/atomic/flags.py
Addresses #1358 
Essentially this issue is a request for other non-standard amino acids to be included in protein subsets such as ca and bb.
> added nonstd aas

- prody/proteins/ciffile.py
Addresses #1364 
The problem was that line 501 starts with ATOMS as part of a sentence and we hadn't accounted for lines like that.
> ciffile fix

- prody/proteins/ciffile.py
Fixes error introduced by #1366. Not all pdb entries have two spaces e.g. 3j77
> fix to ciffile fix

- prody/measure/measure.py
Fixes the following error:
```
~\code\ProDy\prody\measure\measure.py in calcPrincAxes(coords, turbo)
814     """Calculate principal axes from coords"""
815     M = calcInertiaTensor(coords)
--> 816     _, vectors = solveEig(M, 3, zeros=True, turbo=turbo, reverse=True)
817     return vectors
ValueError: too many values to unpack (expected 2)
```
solveEig returns 3 values not 2
> calcPrincAxes fix

- prody/dynamics/essa.py
Fixes #1381 
If there is only one pocket pdb file then parsePDB returns an AtomGroup not a list of AtomGroups, so we check for that and put the single AtomGroup in a list if that is the case.
> scanPockets fix for one pocket

- prody/dynamics/plotting.py
This allows us to get signed values (as below) rather than just absolute ones, but we still get absolute ones by default.
> added non-absolute option to showOverlapTable

- prody/proteins/pdbfile.py
Previously, it only tried parsing mmCIF or EMD files from the database by ID if there wasn't a filename. Now, there's an extra block where it tries if parsePDBStream doesn't return anything too.
> make _parsePDB parse cif and emd files from filenames

- prody/dynamics/pca.py
Without this fix, PCA on an ensemble with fewer than 20 members leads to fewer than 20 modes but vars still has 20 values including those that are basically zero. This then causes a problem for calcSqFlucts.
```
In [4]: pca._eigvals.shape
Out[4]: (16,)
In [5]: pca._array.shape
Out[5]: (8502, 16)
In [6]: pca._vars.shape
Out[6]: (20,)
In [7]: calcSqFlucts(pca)
ValueError                                Traceback (most recent call last)
<ipython-input-7-00fa53df2b79> in <module>
----> 1 calcSqFlucts(pca)
~\code\ProDy\prody\dynamics\analysis.py in calcSqFlucts(modes)
327     V, W, is3d, n_atoms = _getModeProperties(modes)
328
--> 329     sq_flucts = np.dot(V * V, W).sum(axis=1)
330
331     if is3d:
<__array_function__ …
```
> pca vars shape fix

- prody/dynamics/exanm.py
MaskedExANM is made to inherit from MaskedANM (which seems logical to me) and then it gets covered by the check for valid Masked NMA types for saving. Alternatively, we can expand the checks for valid Masked NMA types for saving but that opens us up to having to do that every time we make a new type. 
I've also confirmed that this fix works.
> fix for saving masked exanm

- prody/atomic/atom.py
- prody/atomic/subset.py
Without this fix I get the following error:
```
In [8]: chain.setFlags('hetatm', True)
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-8-a917de4e0178> in <module>
----> 1 chain.setFlags('hetatm', True)
~\code\ProDy\prody\atomic\subset.py in setFlags(self, label, value)
160          :raise AttributeError: when *label* is not in use or read-only"""
161
--> 162         if label in flags.PLANTERS:
163             raise AttributeError('flag {0} cannot be changed by user'
164                                     .format(repr(label)))
UnboundLocalError: local variable 'flags' referenced before assignment
```
With it, everything works as expected:
```
In [4]: …
```
> subset setFlags fix

- prody/proteins/pdbfile.py
This fixes a problem inadvertently incorporated by #1402. It wasn't picked up then because the tests weren't working, but was now picked up in e.g. https://github.com/jamesmkrieger/ProDy/runs/4069323448?check_suite_focus=true
The problem is that _parsePDB raises an error instead of returning None in situations with wrong chain IDs so the one of the tests fails:
```
=================================== FAILURES ===================================
________________________ TestParsePDB.testChainArgument ________________________
pdb = '/home/runner/work/ProDy/ProDy/prody/tests/datafiles/pdb2k39_truncated.pdb'
kwargs = {'chain': '$', 'title': 'pdb2k39_truncated'}
title = 'pdb2k39_truncated', chain = '', ext = '.pdb'
stream = <_io.TextIOWrapper …
```
> _parsePDB fix for bad chains

- prody/proteins/ciffile.py
In mmCIF files, there can be no empty columns and `.` is used instead. For altlocs, this causes problems if we read them as `.` and write that back to PDB files:
```
$ ipython
Python 3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 18:58:29) [MSC v.1916 64 bit (AMD64)]
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.
In [2]: ag = parseMMCIF('7bnm', subset='ca')
@> 3207 atoms and 1 coordinate set(s) were parsed in 0.15s.
In [3]: ag.getAltlocs()
Out[3]: array(['.', '.', '.', ..., '.', '.', '.'], dtype='<U1')
In [4]: writePDB('7bnm_ca_prody.pdb', ag)
Out[4]: '7bnm_ca_prody.pdb'
In [5]: ag2 = parsePDB('7bnm_ca_prody.pdb')
@> WARNING Atomic data could not be parsed, please …
```
> mmcif altloc fix

- prody/proteins/pdbfile.py
Without this fix, we have some very strange residue numbers getting parsed from PDB files:
```
In [2]: ag2 = parsePDB('test2.pdb')
@> WARNING parsed 5 digit residue number including numeric insertion code
@> 29 atoms and 1 coordinate set(s) were parsed in 0.00s.
In [3]: ag2.getResnums()
Out[3]:
array([   1572,    1572,    1572,   15720,   15720,   15720,   15721,
15721,   15721,   15722,   15722,   15722,   15723,   15723,
15723,   15724,   15724,   15724,   15725,   15725,   15725,
-504547, -504546, -504545, -504544, -504543, -504542, -504541,
-504540])
```
The file test2.pdb is the following (taken from pdb1tw7_step3_charmm2namd.pdb from the test files):
```
REMARK AtomMap (Selection 'resnum 1572') + (Selection 'resname CLA')
ATOM      1  OH2 TIP3 1572 …
```
> Resnum fix

- prody/atomic/flags.py
As noted in #1427, CME should be in the non-standard amino acids.
> add cme nonstdaa

- prody/atomic/select.py
In python 3.10, Iterable is now provided in collections.abc instead of collections
> make it compatible with python 3.10

- prody/dynamics/plotting.py
suggested by #1453 
`showProjection(traj, pca[0], by_time=True)` generates the following:
> add by_time to showProj 1D

- prody/atomic/select.py
In `atomic/select.py`, importing `Iterable` from `collections` instead of `collections.abc` causes a `DeprecationWarning` in modern versions of python.  This commit avoids the warning by first trying to import from `collections.abc` before falling back on `collections`.
It'd probably be fine to remove the `collections` import altogether, since `collections.abc` has been present since python 3.3.  But in the interest of being conservative, I just changed the order in which the imports are tried.
> Reorder imports to avoid deprecation warning

- prody/dynamics/clustenm.py
1. We adopted OpenMM 7.6 convention of importing OpenMM, where the name of the top level Python package has changed to remove "simtk". Please check the GitHub page of OpenMM for details.
2. Other minor changes.
> Updates on ClustENMD: importing OpenMM and others

- prody/proteins/pdbfile.py
Without the fix, I get the following error parsing 4ake.cif from a path:
```
Traceback (most recent call last):
File "/home/jkrieger/anaconda3/envs/scipion3/lib/python3.8/site-packages/prody/proteins/pdbfile.py", line 575, in _parsePDBLines
coordinates[acount, 0] = line[30:38]
ValueError: could not convert string to float: '  ? -10.'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/jkrieger/anaconda3/envs/scipion3/lib/python3.8/site-packages/prody/proteins/pdbfile.py", line 124, in parsePDB
return _parsePDB(pdb[0], **kwargs)
File "/home/jkrieger/anaconda3/envs/scipion3/lib/python3.8/site-packages/prody/proteins/pdbfile.py", line 234, in _parsePDB
result = parsePDBStream(stream, **kwargs) …
```
> parsePDB fix for local mmcif

- prody/dynamics/compare.py
Otherwise, using single modes gives the following error:
```
File "/home/jkrieger/anaconda3/envs/scipion3/lib/python3.8/site-packages/prody/dynamics/compare.py", line 215, in calcRWSIP
numerator = np.sum([vars1[l] * vars2[m] * overlap[l, m]**2
File "/home/jkrieger/anaconda3/envs/scipion3/lib/python3.8/site-packages/prody/dynamics/compare.py", line 215, in <listcomp>
numerator = np.sum([vars1[l] * vars2[m] * overlap[l, m]**2
IndexError: invalid index to scalar variable.
```
> calcRWSIP fix for single modes

- prody/database/pfam.py
Fixes #1444 and #1472 
Without the fix, I get the following error:
```
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06) 
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.
In [2]: fasta_file = fetchPfamMSA('PF00186', timeout=1000)
SSLCertVerificationError                  Traceback (most recent call last)
~/anaconda3/envs/scipion3/lib/python3.8/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
1353             try:
-> 1354                 h.request(req.get_method(), req.selector, req.data, headers,
1355 …
```
> fix fetchPfamMSA and searchPfam with request verify False

- prody/proteins/pdbfile.py
This repartitions resnames and chainids to be 3 and 2 characters rather than 4 and 1. Thus 2-char chainids don't overflow.
Otherwise, we get lines that are too long and can't be parsed:
```
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:40:17) 
IPython 7.31.0 -- An enhanced Interactive Python. Type '?' for help.
In [2]: ag = parseMMCIF('4v8r')
@> 128780 atoms and 1 coordinate set(s) were parsed in 2.15s.
In [3]: ag.getChids()
Out[3]: array(['AA', 'AA', 'AA', ..., 'Bz', 'Bz', 'Bz'], dtype='<U2')
In [4]: writePDB('4v8r', ag)
@> WARNING Indices are exceeding 99999 and hexadecimal format is being used for indices
Out[4]: '4v8r.pdb'
In [5]: ag2 = parsePDB('4v8r.pdb') …
```
> Write pdb 2char chid

- prody/proteins/ciffile.py
Without this, the double quotes around atom names with primes in mmCIF files are included in the atom names:
```
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:40:17) 
IPython 7.31.0 -- An enhanced Interactive Python. Type '?' for help.
In [2]: ag = parseMMCIF('4v8r')
@> 128780 atoms and 1 coordinate set(s) were parsed in 2.50s.
In [3]: ag['VD'].getNames()
Out[3]: 
array(['PB', 'O1B', 'O2B', 'O3B', 'PA', 'O1A', 'O2A', 'O3A', '"O5\'"',
'"C5\'"', '"C4\'"', '"O4\'"', '"C3\'"', '"O3\'"', '"C2\'"',
'"O2\'"', '"C1\'"', 'N9', 'C8', 'N7', 'C5', 'C6', 'N6', 'N1', 'C2',
'N3', 'C4'], dtype='<U6')
```
These then get transferred when writing to PDB and make the lines longer:
```
HETATM1f6f4  O3A …
```
> parseMMCIF fix for atomnames with prime

- prody/dynamics/functions.py
- switched parseGromacsModes to mdtraj because mdanalysis is heavier and has more dependencies and installing it could break things more. This means we need to provide a pdb file as a topology, but generally it's not hard to get one. It does use nm like gromacs so not do any silly rescaling of the modes like mdanalysis does.
- made inputs more flexible and made better checks for them
> Gromacs parsing improvements

- prody/proteins/compare.py
As noted in #1464, matchChains has a last line of logging that doesn't make sense if the trival match works:
```
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06) 
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import prody
In [2]: p1 = prody.parsePDB('Runs/000002_ProtImportPdb/extra/4ake.cif')
@> WARNING Trying to parse as mmCIF file instead
@> 3459 atoms and 1 coordinate set(s) were parsed in 0.06s.
In [3]: p2 = prody.parsePDB('Runs/000039_ProtImportPdb/extra/1ake.cif')
@> WARNING Trying to parse as mmCIF file instead
@> 3804 atoms and 1 coordinate set(s) were parsed in 0.09s.
In [4]: cutoff = 90
In [5]: m = prody.matchChains(p1.protein, p2.protein, subset="all", …
```
> matchChains log fix

- prody/apps/prody_apps/prody_align.py
Maybe this is still too subtle, but it should be noted that the align app does something much less sophisticated than users might expect. It just aligns over the single pair of chains that ranks best from matchChains. 
We may also want to update or replace the matchAlign function it uses or provide some kind of option. This probably isn't necessary though.
> update align app usage for matching pair

- prody/atomic/functions.py
Addresses #1341 
We now have two options for assigning blocks, both with a shortest_block option: 
1. Use a number of residues per block with the last block being smaller or longer.
2. Use secondary structure information associated with the atoms provided. This can come from the PDB header or another method such as DSSP or STRIDE.
A *shortest_block* argument is also provided to avoid blocks with too few residues such as termini disconnected from secondary structure elements. 
These options work well including with RTB.
```
Python 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:42:07) 
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import prody
In [2]: atoms = prody.parsePDB("4akeA")
In …
```
> assignBlocks

- prody/proteins/compare.py
Fixes #1483 
This was broken by #1410.
With the fix, we restore the creation of SimpleChain objects that only include protein residues as in ProDy 2.0 and earlier, but also keeps the warnings about other residues besides waters, which are too much.
We now recover the expected behaviour:
```
...: 
...: ref_prot = prody.parsePDB("5RS7")
...: ref_prot = ref_prot.select("chain A")
...: prot = prody.parsePDB("5RVP")
...: res = "1SQ"
...: hv = prot.getHierView()
@> PDB file is found in working directory (5rs7.pdb.gz).
@> 5540 atoms and 1 coordinate set(s) were parsed in 0.06s.
@> Secondary structures were assigned to 232 residues.
@> PDB file is found in working directory (5rvp.pdb.gz).
@> 2870 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> Secondary …
```
> Simple chain fix for non-protein residues

- prody/proteins/__init__.py
- prody/proteins/ciffile.py
- prody/proteins/cifheader.py
- prody/proteins/header.py
- prody/proteins/starfile.py
Finally closes #1356
We can now parse all the same header information from mmCIF files as PDB files, including assigning secondary structures and building biomolecular assemblies:
```
In [1]: import prody
In [2]: import numpy as np
In [3]: cif_ag, cif_hd = prody.parseMMCIF("3h5v.cif", header=True, biomol=True)
@> 9392 atoms and 1 coordinate set(s) were parsed in 0.17s.
@> Secondary structures were assigned to 693 residues.
@> Biomolecular transformations were applied, 2 biomolecule(s) are returned.
In [4]: pdb_ag, pdb_hd = prody.parsePDB("3h5v.pdb", header=True, biomol=True)
@> 9392 atoms and 1 coordinate set(s) were parsed in 0.08s.
@> Secondary structures were assigned to 693 residues.
@> Biomolecular transformations were applied, 2 biomolecule(s) are returned.
In [5]: …
```
> mmCIF header parsing

- prody/proteins/header.py
- prody/proteins/pdbfile.py
With this change, ProDy can now write secondary structure information into PDB files that ProDy can then read back. We are still missing the last part of the SHEET lines about hydrogen bonding between strands, but this can come later.
The output lines otherwise match the lines from the original PDB file and can be used for assigning secondary structures and using them in RTB.
> writePDB secstr

- CONTRIBUTING.md
- docs/devel/develop.rst
I just noticed that there was still bitbucket in the developers instructions but we don't use it anymore
> remove bitbucket

- prody/database/pfam.py
fixes #1496 
Using .content a few lines above meant .read didn't make sense anymore.
> fetchPfamMSA fix

- prody/dynamics/analysis.py
It can of course take NMA objects. Also ndarrays
> calcColl mode arg types

- prody/proteins/compare.py
Without this fix, using CE alignment on all-atom structures is prohibitively slow. Taking only Calpha coords fixes it.
> cealign non-ca fix

- prody/dynamics/functions.py
This allows parseScipionModes to be used outside the Scipion Runs directory tree
> fix missing dir in parseScipionModes

- prody/proteins/ciffile.py
- prody/proteins/cifheader.py
- prody/proteins/starfile.py
fixes #1530 
By using parseSTARSection, we can now handle chemicals as data blocks instead of loops. 
It can also now handle keys that aren't actually present such as carbohydrates and return and empty list. _parseMMCIFLines has been adjusted to cope with that.
> Cif header

- prody/dynamics/functions.py
There can be cases where there isn't a pdb. As pdb was added to allow it to identify GNM modes, the assumption when there isn't one is normal 3D NMA.
> parseScipionModes fix no pdb

- prody/dynamics/analysis.py
The docstring of 'calcAnisousFromModel()' states that a 3Nx6 matrix is returned, but in reality a Nx6 matrix is returned, since there a 6 different `U` values for each atom.
> Fix typo in 'calcAnisousFromModel()'

- prody/atomic/atomgroup.py
- prody/proteins/ciffile.py
- prody/proteins/pdbfile.py
I am recently working on loading the atom connectivity information from pdb files. While parsing files with `parsePDB(file, bond=True)`, I noticed that for several files with missing/unresolved atoms the connectivities are incorrectly assigned to the atomic indices of the `AtomGroup` object. 
Taking further inspections, I noticed that in `prody.proteins.pdbfile._parsePDBLines()` the serial numbers loaded from the CONECT entry are not re-matched to the atom indices. I have created a tentative fix that works correctly for files that I have tested on. A typo in line parsing is corrected alongside.
I am happy to discuss a bit and perform minor code refactoring to get it merged. As a side note, I wonder if prody fully supports loading bond information from mmCIF files?
> Fixing bond (CONECT) loading within pdb file parsing

- prody/apps/prody_apps/prody_pca.py
- prody/tests/atomic/test_atomic.py
Two things to fix:
Without the fixes, these are the problems:
```
======================================================================
ERROR: testPCACommandDCD (prody.tests.apps.test_prody_pca.TestPCACommand)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/mnt/c/Users/james/code/ProDy/prody/tests/apps/test_prody_pca.py", line 55, in testPCACommandDCD
namespace.func(namespace)
File "/mnt/c/Users/james/code/ProDy/prody/apps/prody_apps/prody_pca.py", line 345, in <lambda>
subparser.set_defaults(func=lambda ns: prody_pca(ns.dcd, **ns.__dict__))
File "/mnt/c/Users/james/code/ProDy/prody/apps/prody_apps/prody_pca.py", line 63, in prody_pca
pdb = prody.parsePDB(pdb, altlocs=altlocs)
NameError: name 'altlocs' is not defined …
```
> fixes related to failing tests

- prody/proteins/cifheader.py
- prody/proteins/compare.py
Fixes the following error:
```
In [2]: atoms = parseMMCIF("3p3w")
@> WARNING Could not find _pdbx_nonpoly_scheme in lines.
@> WARNING Could not find _pdbx_branch_scheme in lines.
KeyError                                  Traceback (most recent call last)
Input In [2], in <module>
----> 1 atoms = parseMMCIF("3p3w")
File /mnt/c/Users/james/code/ProDy/prody/proteins/ciffile.py:117, in parseMMCIF(pdb, **kwargs)
115     kwargs['title'] = title
116 cif = openFile(pdb, 'rt')
--> 117 result = parseMMCIFStream(cif, chain=chain, **kwargs)
118 cif.close()
119 return result
File /mnt/c/Users/james/code/ProDy/prody/proteins/ciffile.py:188, in parseMMCIFStream(stream, **kwargs)
186     raise …
```
> cif header fix for 3p3w

- prody/apps/prody_apps/prody_pca.py
Using svd meant that the resulting npz file ends up with too many modes in many cases. It's not possible to index it before saveModel.
> no svd in pca app to allow nmodes control

- prody/proteins/pdbfile.py
warn was used in some blocks but info in others. Now they're all warn.
> parsePDB consistent logging

- prody/proteins/functions.py
Otherwise won't work when called from webpages (e.g. colab) that default
to https since you can't make an insecure connection from a secure
webpage.
> Default to https

- prody/atomic/atomgroup.py
This fixes a bug found when helping with #1572 
Old behaviour: dtype gets overwritten when using setData from an AtomGroup and string length is not maintained. There is a workaround of using `ag.select("all").setData` but we shouldn't need it.
```
...: 
...: ag = parsePDB("6vyb")
@> PDB file is found in working directory (6vyb.pdb).
@> 22365 atoms and 1 coordinate set(s) were parsed in 0.23s.
@> Secondary structures were assigned to 1694 residues.
In [2]: ag.setData("domain", "NTD")
In [3]: ag.setData("domain", "")
In [4]: ag.select("resnum 13 to 303").setData("domain", "NTD")
In [5]: ag.getData("domain")
Out[5]: array(['N', 'N', 'N', ..., '', '', ''], dtype='<U1')
```
New behaviour: if the label already exists then the associated data is used for checking the …
> fix setData to not overwrite dtype

- prody/atomic/fields.py
- prody/proteins/cifheader.py
fixes #1576 
Main error: 'pdbx_pdb_strand_id' is in a data block not a loop so the parsing method I had for polymers didn't work in this case
Incidental 1: the strand/chain id has 3 characters (AAA) so we needed to support that
Incidental 2: having a mismatch in length between chain id (AAA) and seg name (A) allowed the identification of a problem with parsing secondary structure data from mmCIF files where the two were switched.
These are all now fixed and everything works fine.
Previous behaviour: file cannot be parsed with header options such as secondary active (default behaviour). It can be if secondary=False, but the chain ID only has 2 characters:
```
In [2]: ag = parsePDB("4abz")
@> pdb4abz.ent.gz download …
```
> chain id mmCIF fixes

- prody/proteins/ciffile.py
- prody/proteins/cifheader.py
I have been trying to parse an old version of 3h5v.cif and it is causing a number of problems:
1. The first ones are problems with the siguij field being filled with "?" entries (default empty values):
a. We are not using alength for mmCIF parsing and it should be acount instead. This was just missed when adapting parsePDB and not noticed because we weren't parsing siguij data.
```
In [1]: base_path = "/mnt/c/Users/james/OneDrive/Documents/MC_fellowship/2_iGluR/"
In [2]: file_path = (
...:     base_path + "2_1_type/2_1_0_data/2_1_0_1_databases/1_pdb/PBP_pdbs/iGluR/ampar/ntd/"
...: )
In [3]: filename = file_path + "3h5v.cif"
In [4]: from prody import *
...:
...: ag = parsePDB(filename, secondary=False)
NameError …
```
> mmCIF parsing fixes for old 3h5v

- prody/ensemble/pdbensemble.py
- prody/tests/ensemble/test_pdbensemble.py
This resulted in a failure with trimPDBEnsemble after using delCoordset:
```
Input In [227], in <module>
----> 1 h_trim_ens = trimPDBEnsemble(ens)
File /mnt/c/Users/james/code/ProDy/prody/ensemble/functions.py:270, in trimPDBEnsemble(pdb_ensemble, occupancy, **kwargs)
268             msa = msa[:, torf]
269         trans = pdb_ensemble._trans
--> 270         trimmed.addCoordset(confs[:, torf], weights[:, torf], labels, sequence=msa, transformation=trans)
271 else:
272     indices = np.where(torf)[0]
File /mnt/c/Users/james/code/ProDy/prody/ensemble/pdbensemble.py:362, in PDBEnsemble.addCoordset(self, coords, weights, label, **kwargs)
360 if transformations:
361     if len(transformations) != n_repeats:
--> 362         raise ValueError('the number of transformations should be either one or …
```
> bug fix for delCoordset not deleting transformation

- prody/dynamics/signature.py
Labels are needed for various downstream functions including getEigvecs and getArray so they need to be set no matter what. The if conditions we had inside the main if condition were already enough I think without it. They handle the two cases of no labels in the original object and no labels in the input to the function.
> fix mode ens for empty labels in addModeSets

- prody/apps/prody_apps/nmaoptions.py
- prody/apps/prody_apps/prody_anm.py
- prody/apps/prody_apps/prody_gnm.py
- prody/dynamics/gamma.py
```
(scipion3) jkrieger@DESKTOP-QL82H8Q /mnt/c/Users/james/code/ProDy (gamma_godmd) $ ipython
Python 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:42:07) 
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.
In [2]: ag = parsePDB("4akeA", subset="ca")
@> PDB file is found in working directory (4ake.pdb.gz).
@> 214 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> Secondary structures were assigned to 139 residues.
In [3]: gamma = GammaGOdMD(ag)
In [4]: anm = prody.ANM()
In [5]: anm.buildHessian(ag, gamma=gamma)
@> Hessian was built in 0.07s.
In [6]: anm.calcModes()
@> 20 modes were calculated in 0.29s.
```
```
(scipion3) jkrieger@DESKTOP-QL82H8Q …
```
> Gamma from GOdMD

- setup.py
Properly addresses Biopython version compatibility message "Version 1.76 is the last release to support Python 2.7 and 3.5, all later releases require Python 3.6 or greater" and recent requests including in #1546.
I haven't changed pyproject.toml but things seem to work anyway:
```
(scipion3) jkrieger@DESKTOP-QL82H8Q /mnt/c/Users/james/code/ProDy (biop_dep) $ pip install -U biopython
Requirement already satisfied: biopython in /home/jkrieger/anaconda3/envs/scipion3/lib/python3.8/site-packages (1.76)
Collecting biopython
Downloading biopython-1.79-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 25.2 MB/s eta 0:00:00
Requirement already satisfied: numpy in /home/jkrieger/anaconda3/envs/scipion3/lib/python3.8/site-packages …
```
> better biopython dependency

- prody/proteins/compare.py
It is possible for local alignment between pairs of chains to produce an empty list of alignments, resulting in an IndexError in the current code. This patch takes care of this issue.
Original error:
> File .../prody/proteins/compare.py:796, in getAlignedMatch(ach, bch)
>     789 else:
>     790     alignment = pairwise2.align.globalms(ach.getSequence(),
>     791                                          bch.getSequence(),
>     792                                          MATCH_SCORE, MISMATCH_SCORE,
>     793                                          GAP_PENALTY, GAP_EXT_PENALTY,
>     794                                          one_alignment_only=1)
> --> 796 this = alignment[0][0]
>     797 that = alignment[0][1]
>     798 amatch = []
> 
> IndexError: list index out of range
>
> Fix IndexError exception when local pairwise alignment produces 0 alignments

- prody/tests/database/test_pfam.py
Removed the no chain condition because the dictionary in Python 3.5 isn't sorted and doesn't have the same behaviour.
> fix pfam tests for py 3.5

- prody/apps/prody_apps/__init__.py
- prody/apps/prody_apps/prody_energy.py
There is now a `prody energy` app that can fix missing atoms, solvate and calculate energy.
```
(scipion3) jkrieger@DESKTOP-QL82H8Q /mnt/c/Users/james/code/ProDy (energy_app) $ prody --help
usage: prody [-h] [-c] [-v] {anm,gnm,pca,eda,align,blast,biomol,catdcd,contacts,fetch,select,energy} ...
ProDy: A Python Package for Protein Dynamics Analysis
optional arguments:
-h, --help            show this help message and exit
-c, --cite            print citation info and exit
-v, --version         print ProDy version and exit
subcommands:
{anm,gnm,pca,eda,align,blast,biomol,catdcd,contacts,fetch,select,energy}
anm                 perform anisotropic network model calculations
gnm                 perform Gaussian network model calculations
pca                 perform principal component analysis …
```
> added prody energy app

- prody/ensemble/functions.py
We actually do get atom maps back from this argument
> fix atommaps docs

- prody/proteins/header.py
This allows support for more segments for biomol assemblies than 26 repeating ones.
> use 4-digit hy36 numbers for segments

- prody/proteins/pdbfile.py
```
File ~/envs/prody/lib/python3.9/site-packages/prody/proteins/pdbfile.py:1620, in writePQRStream(stream, atoms, **kwargs)
1617         for item2 in sorted_sheet[i-num_strands:i]:
1618             item2.append(num_strands)
-> 1620 num_strands = item[1]
1621 for item2 in sorted_sheet[i-num_strands+1:]:
1622     item2.append(num_strands)
NameError: name 'item' is not defined
```
**I am not sure but it works after modification**
> Error during writeout PQR file

- prody/atomic/atomgroup.py
- prody/atomic/functions.py
- prody/chromatin/hic.py
- prody/dynamics/nmdfile.py
- prody/ensemble/functions.py
- prody/proteins/pdbfile.py
- prody/proteins/starfile.py
- prody/trajectory/psffile.py
- prody/utilities/pathtools.py
**Old behavior:** calling `atom.getFragindex()` without bond info would lead to an error.
**New behavior:** calling `atom.getFragindex()` without bond info would return `None` and a warning.
The reason for this change is that raising an error for calling a `get` function seems to be too harsh. Besides, the new behavior provides an easier way (checking if `None` vs. catching an error) to programmatically check if the bond/fragment information is present.
> Proper handling of fragments when bonds are absent

- prody/ensemble/ensemble.py
Before this change, setting the ensemble's atoms _the second time_ with a subset would subset the ensemble's atoms which is the desired behavior. However, it would not set the underlying atomgroup to the subset's atomgroup, which is inconsistent with the behaviors of calling `ensemble.setAtoms` with any other input types. This may also lead to (hidden) discrepancies between the ensemble's atoms and the atoms the user used to subset.
This issue can be verified by the following script:
```
import prody as pd
prot = pd.parsePDB('3tt1')
ens = pd.Ensemble()
ens.addCoordset(prot)
ens.setAtoms(prot)
title = ens.getAtoms().getTitle()
print(title)
prot2 = prot.copy()
prot2.setTitle("3tt1 copy")
ens.setAtoms(prot2.ca)
title = ens.getAtoms().getTitle()
print(title)
```
**Old behavior:**
```
3tt1 …
```
> Setting the atoms for ensemble even if the atoms is a subset

- prody/proteins/pdbfile.py
Fixes both PDB and PQR writing where sheets have names inconsistent with sorting e.g., S1A, S2A, P1A, P2A, S1B in 2tbv
writePDBStream had an unintentional sorting from numpy unique that is now reversed by using sorted indices
writePQRStream had an actual sorting (that may have been to reproduce the writePDBStream behaviour) that is now removed too
> no sorting of strands in writing

- prody/proteins/ciffile.py
The mmCIF parser was failing to handle the CIF files that pymol was exporting. This tweaks the parser to account for those cases.
1. The doneAtomBlock loop now checks if the atom block continues to the concluding line of the file.
2. The parser now checks whether either 'auth_atom_id' or 'label_atom_id' are present
3. Same, but with 'auth_comp_id' and 'label_comp_id
4. Also with 'auth_seq_id' and 'label_seq_id'
> Fixes to mmcif parsing

- .github/workflows/main.yml
- pyproject.toml
- setup.py
1. Remove python 3.6 as we can't even get it from conda-forge now
2. Require numpy older than 1.24 to keep np.bool and suchlike and use `pip install .` to make it check dependencies
3. Remove python 3.11 as the biopython installation mechanism isn't supported either
> try fixing tests

- prody/atomic/flags.py
- prody/tests/atomic/test_select.py
- prody/tests/datafiles/__init__.py
Some MD simulation systems, such as those from gromacs, lack chain IDs and therefore create sets of atoms with the same residue indices that are not in fact the same residue:
```
In [2]: from prody.tests.datafiles import *
In [3]: pdb_gromacs = prody.parsePDB(
...:     pathDatafile("pdb6fpj_Bb_fixed_solv_ions.pdb"), secondary=True
...: )
@> 83473 atoms and 1 coordinate set(s) were parsed in 1.07s.
In [4]: list(pdb_gromacs.getHierView())
Out[4]: [<Chain: A from pdb6fpj_Bb_fixed_solv_ions (17290 residues, 83473 atoms)>]
In [5]: pdb_gromacs.select("chain A and resnum 2").getResnames()
Out[5]: 
array(['PHE', 'PHE', 'PHE', 'PHE', 'PHE', 'PHE', 'PHE', 'PHE', 'PHE',
'PHE', 'PHE', 'PHE', 'PHE', 'PHE', 'PHE', 'PHE', 'PHE', 'PHE',
'PHE', 'PHE', 'PHE', 'PHE', 'PHE', …
```
> Redefine protein

- prody/tests/ensemble/test_functions.py
- prody/utilities/seqtools.py
The new biopython pairwise aligner outputs are really not so nice and need further processing to avoid problems.
Behaviour from adding the new aligner without the fix:
```
In [2]: ags = parsePDB(
...:     ["prody/tests/datafiles/pdb3hsy.pdb", "prody/tests/datafiles/pdb3o21.pdb"],
...:     biomol=True,
...:     extend_biomol=True,
...:     subset="ca",
...: )
@> 2 PDBs were parsed in 0.17s.                             
In [3]: pdb_ens = buildPDBEnsemble(ags, seqid=50)
@> Mapping 3o21_ca biomolecule 1 to the reference... [ 33%] 1s---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [3], in <module>
----> 1 pdb_ens = buildPDBEnsemble(ags, seqid=50)
File …
```
> aligner bug fix

- prody/chromatin/functions.py
- prody/dynamics/plotting.py
- prody/proteins/functions.py
fixes #1647 and similar issues for showProjection, showEllipsoid and presumably chromatin showEmbedding. I wasn't able to test the chromatin one, but I have managed to confirm that I can make the following figure with both old and new matplotlib as well as using showProtein.
the code is the following using the data from the trajectory analysis files on the prody website:
```
In [2]: import matplotlib.pyplot as plt
...: 
...: plt.ion()
Out[2]: <contextlib.ExitStack at 0x7fd049b2aaa0>
In [3]: ens = parseDCD("mdm2.dcd")
@> DCD file contains 500 coordinate sets for 1449 atoms.
@> DCD file was parsed in 0.02 seconds.
@> 8.33 MB parsed at input rate 343.18 MB/s.
@> 500 coordinate sets parsed at input rate 20600 frame/s.
In [4]: ag = parsePDB("mdm2.pdb")
@> 1449 atoms …
```
> fix axes3d for new matplotlib

- prody/sequence/msa.py
Fixes #1631 and gives the following additional functionality:
```
In [2]: msa1 = parseMSA("prody/tests/datafiles/msa_3hsyA_3o21A.fasta")
@> 2 sequence(s) with 380 residues were parsed in 0.02s.
In [3]: msa1.getLabels()
Out[3]: ['1', '2']
In [4]: msa2 = parseMSA("prody/tests/datafiles/msa_Cys_knot.fasta")
@> 25 sequence(s) with 112 residues were parsed in 0.02s.
In [5]: msa2_ = msa2[1:3]
In [6]: msa2_.getLabels()
Out[6]: ['GTHB2_ONCKE', 'GTHB2_CTEID']
In [7]: merged = mergeMSA(msa1, msa2)
@> WARNING Can only ignore identifiers if all MSAs have the same number of sequences
In [8]: merged = mergeMSA(msa1, msa2, ignore_ids=True)
@> WARNING Can only ignore identifiers if all MSAs have the same number of sequences
In [9]: merged = mergeMSA(msa1, msa2_, …
```
> ignore_ids option for mergeMSA to use different ids

- prody/proteins/localpdb.py
Otherwise, we get the following incorrect behaviour, taking a file with two dots in the filename as the original one and not fetching it again:
```
In [2]: ag = parsePDB("6xr8", compressed=False)
@> PDB file is found in working directory (6xr8.cif_atoms.pdb).
@> 25998 atoms and 1 coordinate set(s) were parsed in 0.24s.
@> Secondary structures were assigned to 0 residues.
```
With the fix, this doesn't happen:
```
In [2]: ag = parsePDB("6xr8", compressed=False)
@> pdb6xr8.ent.gz download failed. 6xr8 does not exist on ftp.wwpdb.org.
@> PDB download via FTP completed (0 downloaded, 1 failed).
@> Downloading PDB files via FTP failed, trying HTTP.
@> WARNING 6xr8 download failed …
```
> only split twice in fetchPDB if ending is gz

- prody/proteins/compare.py
This check is very ancestral and should have been removed a while ago. ProDy now depends on Biopython and handles pairwise alignment versions fine and the importBioPairwise2 function doesn't exist anymore, so we wouldn't have a case where the pairwise2 option isn't available and this variable is set to False.
This was picked up in #1653 in response to changes related to non-protein residues
> remove pairwise2 check

- prody/trajectory/trajectory.py
fixes #1660 
The problem was with how the frame was initiated when there were atoms. It was pointing to an attribute of the Trajectory object that was changing.
> trajectory next frame fix

- prody/proteins/ciffile.py
Helps with #1666 
New behaviour:
```
In [2]: structure = parseMMCIF("2jfz")
In [3]: list(structure.getHierView())
Out[3]: 
[<Chain: A from Segment A from 2jfz (255 residues, 2012 atoms)>,
<Chain: B from Segment B from 2jfz (249 residues, 1959 atoms)>,
<Chain: A from Segment C from 2jfz (1 residues, 33 atoms)>,
<Chain: A from Segment D from 2jfz (1 residues, 10 atoms)>,
<Chain: B from Segment E from 2jfz (1 residues, 33 atoms)>,
<Chain: B from Segment F from 2jfz (1 residues, 10 atoms)>,
<Chain: A from Segment G from 2jfz (228 residues, 228 atoms)>,
<Chain: B from Segment H from 2jfz (222 residues, 222 atoms)>]
In [4]: structure = parseMMCIF("2jfz", unite_chains=True)
In [5]: list(structure.getHierView())
Out[5]: 
[<Chain: A from Segment A from 2jfz (485 …
```
> add unite_chains option to parseMMCIF

- prody/dynamics/plotting.py
It may be a thing from the latest seaborn, but kdeplot doesn't support multi-dimensional data the way we're providing it and gives errors about the number of arguments, so it's easier to provide x and y specifically
> fix 2d kde plot

- prody/proteins/starfile.py
relion and scipion star files can have a field name and then a number, not just a name
> star fix for relion and scipion loop format

- prody/utilities/seqtools.py
Fixes #1689 
3 main changes:
1. take the first alignment rather than looping. There can be a huge number e.g. 37M for 1n5y_L and 1dlo_A!
2. calculate begin and end more efficiently
3. extend rows much more efficiently
This now works fine, including with buildPDBEnsemble
> fix biopairwise going forever

- prody/utilities/catchall.py
This allows matrices to be plotted with different size dots by using scatter with markersize. Default behaviour when markersize is not set remains the same
> Show matrix markersize scatter option

- prody/proteins/compare.py
- prody/sequence/analysis.py
- prody/sequence/msa.py
- prody/utilities/seqtools.py
improved fix to #1689. This was missed in #1700 
I can confirm this still works with buildPDBEnsemble
New result from the function itself:
```
In [2]: ag1 = parsePDB('1n5y', subset='ca')
@> 1n5y downloaded (1n5y.pdb.gz)
@> 1423 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> Secondary structures were assigned to 748 residues.
In [3]: ag2 = parsePDB('1dlo', subset='ca')
@> 1dlo downloaded (1dlo.pdb.gz)
@> 971 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> Secondary structures were assigned to 481 residues.
In [4]: a_sequence = …
```
> alignBioPairwise max alns fix

- prody/apps/prody_apps/nmaoptions.py
- prody/apps/prody_apps/prody_anm.py
- prody/apps/prody_apps/prody_gnm.py
- prody/apps/prody_apps/prody_pca.py
Default behaviour is to not save matrices to npz files as before but now there is an option to add them -Z or --npzmatrices
```
(scipion3) jkrieger@whipple ~/software/scipion3/software/em/ProDy (prody-master) $ prody anm 3h5vA --npz
@> 3h5v downloaded (3h5v.pdb.gz)
@> 3225 atoms and 1 coordinate set(s) were parsed in 0.08s.
@> Secondary structures were assigned to 237 residues.
@> 376 atoms will be used for ANM calculations.
@> Using gamma 1.0
@> Hessian was built in 0.16s.
@> 10 modes were calculated in 0.15s.
@> Writing numerical output.
(scipion3) jkrieger@whipple ~/software/scipion3/software/em/ProDy (prody-master) $ ls *npz
3h5vA_anm.anm.npz
(scipion3) jkrieger@whipple …
```
> add matrices to apps

- prody/dynamics/nma.py
- prody/tests/dynamics/test_enms.py
The main difference is the inclusion of a missing -1 on the number of modes for the start of the slice
> fix nma indexing errors

- prody/apps/prody_apps/prody_anm.py
- prody/dynamics/gamma.py
- prody/proteins/compare.py
GammaGOdMD is renamed as GammaED and its origin is acknowledged properly as ed-ENM. There is also an alias to keep the name GammaGOdMD.
The default mapping is also explained properly as this was missing.
> Improve ed-ENM and docs

- prody/proteins/cifheader.py
addresses #1685 
1. parseCIFHeader can get results from any key:
```
In [2]: header = parseCIFHeader('7E1B.cif', '_pdbx_unobs_or_zero_occ_residues')
In [3]: header
Out[3]: 
[OrderedDict([('_pdbx_unobs_or_zero_occ_residues.id', '1'),
('_pdbx_unobs_or_zero_occ_residues.PDB_model_num', '1'),
('_pdbx_unobs_or_zero_occ_residues.polymer_flag', 'Y'),
('_pdbx_unobs_or_zero_occ_residues.occupancy_flag', '1'),
('_pdbx_unobs_or_zero_occ_residues.auth_asym_id', 'A'),
('_pdbx_unobs_or_zero_occ_residues.auth_comp_id', 'MET'),
('_pdbx_unobs_or_zero_occ_residues.auth_seq_id', '1'),
('_pdbx_unobs_or_zero_occ_residues.PDB_ins_code', '?'),
('_pdbx_unobs_or_zero_occ_residues.label_asym_id', 'A'),
('_pdbx_unobs_or_zero_occ_residues.label_comp_id', 'MET'), …
```
> cif header custom keys and unobserved

- prody/proteins/__init__.py
- prody/proteins/waterbridges.py
New module for detection and analysis of water bridges in proteins.
Water bridges are hydrogen bonds formed when water molecules bridge between two or more protein residues, creating a hydrogen-bonding network stabilising protein-protein and protein-ligand interactions. The developed code aims to identify and analyze conserved water molecules and protein regions involved in interactions mediated by water bridges. This will benefit the scientific community in understanding protein interactions and stability.
More information on the methodology can be found [here](https://drive.google.com/file/d/1CmD1F66DqQwt4_PKWM5fq-NWRZtWCYFf/view?usp=sharing).
`calcWaterBridges` returns calculated bridges in one of three output types:
1. indices -bridge is just a list of indices of atoms involved in a …
> Water bridging module

- prody/proteins/pdbfile.py
Some structures can have multi-character chain identifiers (see 6Z4H). Really Bad Things happen when trying to write these out.
> Make sure PDB chain id is only a single character.

- prody/proteins/pdbfile.py
We now set both as False by default (set in _parsePDBLines) so if there's an extra character in between then it gets ignored.
setting long_resname=True makes it part of the resname and setting long_chid=True makes it part of the chid
> parsePDB long resname and long chid options

- prody/dynamics/functions.py
If there are indices, then we make a dummy NMA or GNM object with padding entries of ones and make a ModeSet from it.
> handle indices not starting at 1 in parseScipionModes

- prody/dynamics/functions.py
This allows it to parse indices and create a dummy ModeSet for Scipion's projection viewer, but not otherwise
> option parseIndices default False

- prody/database/dali.py
The assumption that the query is the first item in the hits isn't always right, so we shouldn't skip the first item. Sometimes the query isn't there at all. I suspect that DALI is using an old version of the PDB.
Also, it should permit cutoff_len=0 and switch to cutoff_len with integers when it's > 1.
> fix dali filtering

- prody/proteins/pdbfile.py
- prody/tests/proteins/test_pdbfile.py
fixes a problem created by #1783 because I didn't think about using writePDB on ensembles
> only get and set acs ind if hasattr

- prody/proteins/ciffile.py
- prody/proteins/cifheader.py
- prody/proteins/mmtffile.py
- prody/proteins/starfile.py
There are just so many of them otherwise and they're not really useful.
Most of them are removed by adding a report argument to parseSTARSection and setting it to False for CIF parsing (the default is True to maintain old behaviour for other uses).
I also removed the unnecessary true/except/else block for anisotropic B factors. It's sufficient to just check if there's data and use it if there is.
> Fewer warnings

- prody/proteins/ciffile.py
- prody/proteins/emdfile.py
- prody/proteins/localpdb.py
fixes #1482 
New behaviour:
```
In [2]: ag = parseCIF("6qkc", compressed=False)
@> CIF file is found in working directory (6qkc.cif).
@> WARNING Could not find _pdbx_branch_scheme in lines.
@> WARNING Could not find _pdbx_struct_mod_residue in lines.
@> WARNING Could not find _pdbx_struct_mod_residue in lines.
@> WARNING Could not find _atom_site_anisotrop in lines.
@> WARNING No anisotropic B factors found
@> 13794 atoms and 1 coordinate set(s) were parsed in 0.88s.
@> Secondary structures were assigned to 1037 residues.
In [3]: emdmap = parseEMD('4572')
@> EMD file is found in working directory (4572.map).
@> Output is an EMDMAP with 1.40 A/pix.
In [4]: ag = parseEMD('4572', n_nodes=100)
@> EMD file is found in working directory (4572.map).
@> Building …
```
> look for cif and emd in path

- prody/proteins/ciffile.py
- prody/proteins/cifheader.py
- prody/proteins/starfile.py
- prody/tests/database/test_pfam.py
This gives the user the chance to keep the warnings removed by #1794 if they want to
> add report as argument for ciffile and cifheader

- prody/database/pfam.py
- prody/proteins/ciffile.py
- prody/tests/database/test_pfam.py
partially helps with #1790 
We still need a fix for MMTF
> adhoc fix for 6uwi for mmCIF

- prody/proteins/interactions.py
I added atom_terms parameter, more information can be retrieved from SMINA, and I fixed stop_frame in multi-model PDB.
The code of calcSminaBindingAffinity is now more compact after improvements.
> New features in calcSminaBindingAffinity

- prody/proteins/ciffile.py
- prody/tests/proteins/test_ciffile.py
Otherwise, we get an index error with altloc='all'
> fix default altloc mask size for parseMMCIF

- prody/tests/database/test_pfam.py
Ideally, we should fix the pfam code and figure out why we get only 2 out of 4 domains, but this test should work either way
> fix pfam test for pfam changes

- prody/proteins/compare.py
Otherwise, the trivial mapping is accepted if seqid is >=90 % even if the user wants more stringency e.g. 96 %
Without the fix, the trivial mapping gets included in the ensemble:
```
@>   Comparing Chain B from 7wz1 (len=1027) with Chain A from 7dx1:
@>      Mapped: 961 residues match with 95% sequence identity and 99% overlap.
@> Trying to map atoms based on residue numbers and identities:
@>   Comparing Chain A from 7wz1 (len=1032) with Chain B from 7dx1:
@>      Mapped: 964 residues match with 95% sequence identity and 99% overlap.
@> Trying to map atoms based on residue numbers and identities:
@>   Comparing Chain C from 7wz1 (len=1033) with Chain C from 7dx1:
@>      Mapped: 964 residues match with 95% sequence identity and 99% overlap.
@> Finding the atommaps based on their …
```
> override GOOD_SEQID and GOOD_COVERAGE with seqid and coverage if higher

- prody/dynamics/plotting.py
Running showTree_networkx with default parameters fails to label nodes with the following error:
```
TypeError                                 Traceback (most recent call last)
Input In [7], in <cell line: 1>()
----> 1 showTree_networkx(seqid_tree)
File ~/software/scipion3/software/em/ProDy/prody/dynamics/plotting.py:2281, in showTree_networkx(tree, node_size, node_color, node_shape, withlabels, scale, iterations, k, **kwargs)
2278 networkx.draw_networkx_edges(G, pos=layout)
2280 if np.isscalar(node_shape):
-> 2281     networkx.draw_networkx_nodes(G, pos=layout, withlabels=False, node_size=sizes, 
2282                                     node_shape=node_shape, node_color=colors)
2283 else:
2284     for shape in …
```
> fix networkx for updated versions

- prody/proteins/fixer.py
- prody/proteins/waterbridges.py
- prody/tests/database/test_pfam.py
1. Added a function fixStructuresMissingAtoms for applying addMissingAtoms to many structures
2. Added a function filterStructuresWithoutWater to filter structure without water or with not enough water
This allows us to run the following pipeline:
```
In [2]: pdbids = ['5UOJ', '1A9U', '1BL6', '1BL7', '1BMK', '1DI9', '1IAN']
In [3]: infiles = fetchPDB(pdbids, compressed=False)
In [4]: new_pdbids = fixStructuresMissingAtoms(infiles, method='pdbfixer')
@> WARNING outfile addH_5uoj.pdb already exists, so returning it. Set overwrite=True to overwrite it
@> WARNING outfile addH_1a9u.pdb already exists, so returning it. Set overwrite=True to overwrite it
@> WARNING outfile addH_1bl6.pdb already exists, so returning it. Set overwrite=True to overwrite it
@> WARNING …
```
> Streamline fixer and water filter for multiple structures

- prody/measure/measure.py
Fixes this error, picked up building the website
```
In [1]:        from prody import *
...:        protein = parsePDB('1ejg')
...:        calphas = protein.select('calpha')
...:        adp_matrix = buildADPMatrix(calphas)
@> 1ejg downloaded (1ejg.pdb.gz)
@> 637 atoms and 1 coordinate set(s) were parsed in 0.01s.
ValueError                                Traceback (most recent call last)
Cell In[1], line 4
2 protein = parsePDB('1ejg')
3 calphas = protein.select('calpha')
----> 4 adp_matrix = buildADPMatrix(calphas)
File ~/code/ProDy/prody/measure/measure.py:814, in buildADPMatrix(atoms)
812     element[0, 2] …
```
> fix adp matrix

- prody/proteins/__init__.py
- prody/proteins/waterbridges.py
New function selectSurroundingsBox selects the surroundings of a selection in a bounding box with the minimum and maximum x, y and z values, and an optional padding. There is an option to just return the x, y, z selection string.
calcWaterBridges and calcWaterBridgesTrajectory have new kwargs selstr and expand_selection to take the output of this function or any other user selstr.
By default, expand_selection is False to not have unexpected results for other selections. If set to True, then it uses the new function after applying the initial selstr.
```
...: 
...: atoms = parsePDB('4a0v_all_sci.pdb')
...: traj = parseDCD('4a0v_all_sci_3frames.dcd')
@> 707044 atoms and 1 coordinate set(s) were parsed in 9.51s.
@> DCD file contains 4 coordinate sets for 707044 …
```
> add selstr and box selection to watfinder

- prody/database/dali.py
This is required to match the case of the query to include it in the filtered set. Without this, [the signdy dali tutorial](http://www.bahargroup.org/prody/tutorials/signdy_tutorial/overview.html) gives an ensemble with too many residues as a result of taking the next structure as the reference and the results are much less interpretable.
> fix case for dali pdbId and chain

- prody/apps/prody_apps/prody_catdcd.py
Otherwise, first isn't taken into account and catdcd still started with frame 0 regardless of the value. It was just affecting how many frames were written.
> add first to catdcd goto

- prody/dynamics/plotting.py
Without the fix, we get overlapping of chains after the second one onto the second one:
```
In [1]: import matplotlib.pyplot as plt; plt.ion()
Out[1]: <matplotlib.pyplot._IonContext at 0x7fa8eb592940>
In [2]: from prody import *
In [3]: ag = parsePDB('7kec')
In [4]: atoms = ag.ca
In [5]: showAtomicLines(atoms.getBetas(), atoms=atoms, gap=True)
```
With the fix, everything is as it should be:
> fix showAtomicLines gaps

- prody/proteins/waterbridges.py
Without this fix, we can see on the last pull request that we get the same number of water bridges for groups of frames.
Having the option to not use the parallel code when max_proc=1 is also a good thing to have.
> Fix frame update and allow non-parallel

- prody/proteins/waterbridges.py
- Critical fix when using start frame - otherwise, it doesn't analyse enough frames
For both trajectory and multi-model PDB
- added use_segname to getResidueName for use with calcBridgesResiduesHistogram
- made selectSurroundingBox select whole residues
Now, we should get sensible results
> More improvements and fixes

- README.rst
This should fix the ones on PyPI when we make a release too
> fix links in readme

- prody/proteins/waterbridges.py
This is a critical fix that needs to go into the release. Otherwise, watfinder trajectory analysis wouldn't work for model-model pdb inputs with max_proc == 1.
> fix max_proc 1 multi-model atoms

- prody/compounds/pdbligands.py
fixes #1870 
We may still need to remove or redo fetchPDBLigands, but everything should be fine for now
This makes parsePDBLigand and PDBLigandRecord work now by using parseCCD:
```
In [2]: x = parsePDBLigand('STI')
In [3]: x
Out[3]: <prody.compounds.pdbligands.PDBLigandRecord at 0x7f4823bb2df0>
In [4]: x._rawdata
Out[4]: <StarDataBlock: STI (24 entries and 6 loops)>
In [5]: x.getCanonicalSMILES()
Out[5]: 'Cc1ccc(cc1Nc2nccc(n2)c3cccnc3)NC(=O)c4ccc(cc4)CN5CCN(CC5)C'
```
> Parse ligands fixes

- prody/proteins/localpdb.py
Otherwise, prody keeps downloading pdb files again and again if we don't say compressed=False:
```
(prody-github) jkrieger@whipple ~/software/scipion3/software/em/prody-github/ProDy (main) $ rm 8c2*
(prody-github) jkrieger@whipple ~/software/scipion3/software/em/prody-github/ProDy (main) $ ipython
Python 3.9.19 (main, May  6 2024, 19:43:03) 
IPython 8.15.0 -- An enhanced Interactive Python. Type '?' for help.
In [2]: protein = prody.parsePDB('8C2H')
@> 8c2h downloaded (8c2h.pdb.gz)
@> 9912 atoms and 1 coordinate set(s) were parsed in 0.08s.
In [3]: protein = prody.parsePDB('8C2H')
@> Connecting …
```
> fix localpdb gz check

- prody/utilities/eigtools.py
- pyproject.toml
- setup.py
fixes #1955 
later scipy uses the driver argument instead of turbo. The default value is 'evr' for standard problems and driver='evd' can be faster at the expense of memory so matches turbo. The deprecation warning says 'gvd' but actually we don't have a generalised problem as we don't provide a second matrix b.
> eigh evd when no turbo

- prody/atomic/functions.py
fixes #1962 
for some reason HierView getResidue gets atoms from multiple residues for GLN 357 and it's fixed in the list comprehension of _getResidue so we only have one entry in the list. So, it throws an error that there's a list when really we can extract it, which we now do.
> extract res if only 1 in extendAtoms

- prody/proteins/interactions.py
- prody/proteins/waterbridges.py
I fixed a problem with calcStatisticsInteractions(), added some info warnings for InSty tool and WatFinder.
I also added a new function showInteractionsHist(), which generates bar plots with interactions (see below).
Now we have two options - bar plot and graph like the one below.
> InSty improvements

- prody/proteins/waterbridges.py
I modified findClusterCenters() to include other selections, not only water.
> WatFinder - findClusterCenters() extension

- prody/proteins/interactions.py
I did the following things:
(1) added getInteractors() to obtain interactions for a particular residue
interactions.getInteractors('LEU1322A')
@> hb:VAL1335A-LEU1322A
@> hp:LEU1322A-PHE1304A
@> hp:TRP1389A-LEU1322A
@> hp:ILE1374A-LEU1322A
@> hp:VAL1335A-LEU1322A
(2) fixed getFrequentInteractors()
Before, we were overwriting one type of interaction if we had two for the same pair, and we didn't include reverse pairs.
It means that when we had such interactions for LEU1322A:
'hb:VAL1335A-LEU1322A',
'hp:LEU1322A-PHE1304A',
'hp:TRP1389A-LEU1322A',
'hp:ILE1374A-LEU1322A',
'hp:VAL1335A-LEU1322A'
We were obtaining only:
'hp:TRP1389A-LEU1322A',
'hp:ILE1374A-LEU1322A',
'hp:VAL1335A-LEU1322A'
because 'hb:VAL1335A-LEU1322A' was overwritten by  'hp:VAL1335A-LEU1322A', and  'hp:LEU1322A-PHE1304A' was …
> Interactions insty fixes

- prody/proteins/cifheader.py
- prody/proteins/localpdb.py
- prody/proteins/pdbfile.py
- prody/proteins/wwpdb.py
- prody/tests/proteins/test_wwpdb.py
some things to get tests working again in response to #1605
> PDB FTP hot fixes

- prody/dynamics/clustenm.py
The 1st fix is regardless of openmm version. Other fixes can be towards accommodating the new openmm (#1971) in the same pull request.
The default value of nproc for passing on to solvEig couldn't be None because there's a numeric comparison happening and should be 0 instead.
```
clustenm.run(n_modes=2, n_confs=5, n_gens=2, maxclust=2, sim=False, rmsd=2)
@> Kirchhoff was built in 0.04s.
@> Generation 0 ...
@> Minimization in generation 0 ...
@> Completed in 17.70s.
@> #-------------------/*\-------------------#
@> Generation 1 ...
@> Sampling conformers in generation 1 ...
@> Hessian was built in 0.13s.
TypeError                                 Traceback (most recent call last)
Cell In[7], line 1
----> 1 …
```
> clustenm fixes

- prody/proteins/interactions.py
When there are no hydrogen bonds between chains with the current parameters, we can get this error if there's no ligand either, but it works if we loosen the criteria.
```
In [2]: PDBfile = 'addH_9asd.pdb'
In [3]: atomsRL = parsePDB(PDBfile).select('protein and chain R L')
In [4]: chHB_RL = calcChHydrogenBonds(atomsRL)
Cell In[4], line 1
----> 1 chHB_RL = calcChHydrogenBonds(atomsRL)
File ~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/interactions.py:713, in calcChHydrogenBonds(atoms, **kwargs)
711 ChainsHBs = [ i for i in HBS_calculations if str(i[2]) != str(i[5]) ]
712 if not ChainsHBs:
--> …
```
> bug fix chainsHB no ligand

- prody/proteins/interactions.py
We have multiple options for using kwargs so that we can control individual types of interactions or all of them at once, so I updated the docs accordingly
For example, we can do this. The first change (using distDA) just affects H bonds (first entry) and the second change (using distA) affects all of them.
```
In [2]: PDBfile = 'addH_9asd.pdb'
In [3]: atomsRL = parsePDB(PDBfile).select('protein and chain R L')
In [4]: interactions = Interactions()
In [5]: all_interactions = interactions.calcProteinInteractions(atomsRL)
In [6]: [len(ints) for ints in all_interactions]
Out[6]: [50, 6, 0, 6, 4, 60, 5]
In [7]: all_interactions = interactions.calcProteinInteractions(atomsRL, distDA=4)
In [8]: [len(ints) for ints in all_interactions]
Out[8]: [68, 6, 0, 6, 4, 60, 5] …
```
> Better InSty kwarg docs

- prody/proteins/interactions.py
It's just for the user input and then the function uses angle_min and angle_max internally anyway
> replace PiStack angle_min_RB and angle_max_RB with PS versions

- prody/proteins/interactions.py
Now we cite the paper for IB_solv and IB_nosolv and credit people for CS
I don't know if we want to add more for CS. Maybe we can add the InSty paper when we have it and that will be enough.
> expand matrix energy docs

- prody/proteins/fixer.py
This permits us to run addMissingAtoms twice, adding missing heavy atoms with pdbfixer and hydrogens with openbabel:
```
filename1 = addMissingAtoms('9asd.pdb', method='pdbfixer', add_hydrogens=False, outfile='model_9asd.pdb')
PDBfile = addMissingAtoms(filename1, method='openbabel')
```
This often leads to better hydrogen placement than using pdbfixer for everything, permitting more interactions to be captured more easily.
> add option to not add hydrogen

- prody/proteins/interactions.py
Otherwise, we get an error if the matrix isn't calculated. Now there's it will build the matrix if it's not there and the option to overwrite it if it is.
> add build and overwrite to showCumulativeInteractionTypes energy

- prody/proteins/interactions.py
Otherwise, we get a failure when one of the interaction types has 7 interactions. I've improved the check so that it knows that it has 7 lists of lists rather than just 7 items.
> better 7 types check for writing tcl

- prody/dynamics/plotting.py
Otherwise, showProjection expects multiple labels and weights instead of markersize, so code in the ClustENMD tutorial doesn't work
This tutorial is verbatim to run large calculations, so it wasn't spotted until I copied it for the ANMD tutorial.
> restore one label and markersize to showProjection

- prody/proteins/ciffile.py
I needed these fixes to parse an mmCIF file I received, which I think comes from Phenix refinement
> broader if conditions for parsing nonstandard cif files

- prody/database/dali.py
We can now get multimers that don't have that number of chains by reversing the filtering.
```
import os
if not os.path.exists('3h5vA_dali.txt'):
x = searchDali('3h5vA')
x.fetch(timeout=10000)
else:
x = DaliRecord('3h5vA_dali.txt', 
'3h5v', 'A', localFile=True)
y = x.filter(cutoff_Z=41.3, cutoff_rmsd=2, stringency=True)
pdb_ids = list(set([result[:4] for result in y]))
ags = parsePDB(pdb_ids, biomol=True, extend_biomol=True, 
subset='ca')
print('number of biomols: ' + str(len(ags)))
dimers = daliFilterMultimers(ags, x, n_chains=2)
print('number of dimers: ' + str(len(dimers)))
non_dimers = daliFilterMultimers(ags, x, n_chains=2,
reverse=True)
print('number of non-dimers: ' + str(len(non_dimers)))
```
```
@> Obtained 5391 PDB chains from Dali for 3h5vA.
@> 5134 PDBs …
```
> add reverse to filterDaliMultimers

- prody/proteins/interactions.py
I removed "Bond" word from the title of the plot created by calcSignatureInteractions('struc_homologs', mapping_file='shortlisted_resind.msa')
Otherwise, we would have Pi-Cation Bond, HPh Bond in the title.
I did that a week ago or so, but I forgot to pull request.
Now we have:
> SignInt - change in the title name of 

- prody/proteins/interactions.py
So far, I just have a fix to the single selection mode, which didn't include chain, but I'm close to making the whole thing more general too.
> fix filterInteractions to be more general

- README.rst
We probably have more to fix because I'm getting complaints about the readme using twine to push to the test PyPI, but this one is needed either way
> Readme fix: remove double back tick

- prody/dynamics/anmd.py
PCA has variances as eigvals, so we need to take the reciprocal to get equivalent eigvals for scaling.
> anmd fix for pca input

- prody/proteins/interactions.py
These could be quite helpful to have
> add other dali filter arguments to runDali

- .github/workflows/main.yml
Seeing as github actions doesn't build prody and biopython extensions anymore for python 2.7, let's remove it
> remove py27 from github actions

- prody/atomic/select.py
This removes warnings in newer python versions.
> Fix regex strings - should be raw

- prody/proteins/header.py
- prody/tests/proteins/test_header.py
The is the new and cleaned up PR for extending prody/protein/header.py to parse CRYST',  SCALE, REMARK 465 (missing_residues), and REMARK 470 (missing_atoms). I also extended prody/tests/protein/test_header.py to test these new parsers.
I am using these records to complete structures and find crystal packing contacts.
NOTE: the code is unchanged from the previous PR (that I withdrew), but this time I branched from from version 2.5.0 for cleaner commit history. Sorry for the inconvenience.
> extended header parsing

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/prody-bug-report.md
This adds a template for Bug Reports going to the Issues tab. This should help ensure more productive questions and responses and reduce back-and-forth gathering information about version, OS etc.
> Create a template for new issues

- .github/workflows/main.yml
- prody/proteins/ciffile.py
- prody/proteins/interactions.py
- prody/tests/database/test_bioexcel.py
- setup.py
> support mmcif with no b fac and occ

- prody/dynamics/clustenm.py
This allows ClustENM to be used with versions of OpenMM over 8. The issue was a unit mismatch in the tolerance parameter for energy minimization. Something must have changed on their end going from v7 to v8.
> ClustENM compatibility with OpenMM v8 and above

- .github/workflows/main.yml
- prody/proteins/hpbmodule/README
The Python 3.9 tests are failing, while newer versions of Python are not. I removed the need to test 3.9 from the CI and I think going forward, we can support the most recent Python version plus the previous 2.
> End support for python 3.9

- prody/proteins/ciffile.py
Added the ability to parse ATOM/HETATM entries that are spread across 2-lines.
> mmcif parsing across 2 lines

- prody/ensemble/functions.py
Otherwise, we get an error when they don't have it as exemplified in this Scipion protocol run from an old ensemble:
```
File "/home/spa/scipion3/scipion-em-prody/prody2/protocols/protocol_cluster.py", line 140, in ensembleModificationStep
ensFn = prody.saveEnsemble(self.ens, self.ensBaseName)
File "/home/spa/scipion3/software/em/prody-github/ProDy/prody/ensemble/functions.py", line 100, in saveEnsemble
np.savez(ostream, **attr_dict)
File "<__array_function__ internals>", line 200, in savez
File "/home/spa/anaconda3/envs/scipion3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 615, in savez
_savez(file, args, kwds, False)
File "/home/spa/anaconda3/envs/scipion3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 719, in _savez
format.write_array(fid, val,
File …
```
> add _bondOrder and _bondIndex to saveEnsemble and loadEnsemble

- prody/atomic/atomic.py
alternative fix to #2111 
This bypasses the biopython issue of changing model 0 to 1 by starting at 1 instead of fixing it. That seems like the recommended behaviour anyway.
> update toBioPythonStructure init_model

- prody/proteins/ciffile.py
- prody/proteins/cifheader.py
- prody/proteins/starfile.py
- prody/tests/datafiles/__init__.py
- prody/tests/datafiles/mmcif_1ake_chimerax.cif
- prody/tests/proteins/test_ciffile.py
There was a string of errors from trying to parse header information, such as biomols, from a chimerax cif file generated by scipion, which is now included in the tests datafiles. These commits should fix it.
> Handle chimerax cif (missing fields)

- prody/database/pfam.py
- prody/proteins/pdbfile.py
- prody/tests/database/test_pfam.py
- prody/utilities/seqtools.py
partial fix to #1933 
Before the fix, ProDy doesn't realise that the execution of searchPfam is bad (the input should be a Uniprot ID not a Pfam ID) and raises an error related to not finding results:
```
In [2]: searchPfam('PF00047')
@> Retrieving Pfam search results: https://www.ebi.ac.uk/interpro/wwwapi/entry/all/protein/uniprot/PF00047
/home/jkrieger/software/miniconda/envs/prody-github/lib/python3.10/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ebi.ac.uk'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
warnings.warn(
@> Pfam search completed in 0.30s. …
```
> extend pfam errors and fix parsePfamPDBs

- prody/proteins/pdbfile.py
This enables us to have non-stripped icodes, so they can be used for selections. The default is True to maintain the old behaviour.
This should help with the problem found in #2100 
```
In [2]: ag = parsePDB('1ucy', compressed=False)
@> PDB file is found in working directory (1ucy.pdb).
@> 8165 atoms and 1 coordinate set(s) were parsed in 0.07s.
In [3]: ag.select('chain L and resnum 14').getIcodes()
Out[3]: 
array(['', '', '', '', '', '', '', '', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
'A', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'C',
'C', 'C', 'C', 'C', 'C', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D',
'D', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'F', 'F', 'F',
'F', 'F', 'F', 'F', 'F', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
'G', 'G', 'G', 'H', 'H', …
```
> add kwarg strip_icodes to parsePDB parsePQR

- prody/proteins/__init__.py
- prody/proteins/ciffile.py
- prody/proteins/pdbfile.py
- prody/proteins/wwpdb.py
- prody/utilities/misctools.py
The first mmCIF files with extended pdb ids are here: https://www.rcsb.org/news/feature/67edb35096cbbd16fc52edaf
Now, we have some start at being able to support them.
```
In [2]: ag = parsePDB('pdb_00006uv8')
@> Downloading PDB files via FTP failed, trying HTTP.
@> WARNING pdb_00006uv8 download failed ('https://files.rcsb.org/download/PDB_00006UV8.pdb.gz' could not be opened for reading, invalid URL or no internet connection).
@> PDB download via HTTP completed (0 downloaded, 1 failed).
@> WARNING Trying to parse mmCIF file instead
@> CIF file is found in working directory (pdb_00006uv8.cif).
@> 1554 atoms and 1 coordinate set(s) were parsed in 0.02s.
```
> start supporting extended pdb id
